### ISSUE TITLE
Difference between API vs No API ?

### ISSUE THREAD

**Issue by DonCorleone9** [ArdiArtani/Google-Drive-Player-Script#104]
Hey @ArdiArtani
2 questions: 

1) I saw your commit 11 days ago and it uses the google API. I am using a previous version of the drive script. I wanted to know.. What is the difference between using the Drive API version and the one without it ? I ask because the way i have modified this script to use with WP will require a lot of changes to make this work.. Can i continue to use the one without the API ?

2) Also, does the API key have to be from the same account as the video uploader ?

Thanks :)

**Comment by ArdiArtani** [comment]
Hello @DonCorleone9, since Google did some changes, the previous version wasn't working anymore so I came up with another temporary solution until I find another one that doesn't use Drive API. For your second question no it doesn't matter as long as you have an API key
