### ISSUE TITLE
Simple solution

### ISSUE THREAD

**Issue by CardealRusso** [ArdiArtani/Google-Drive-Player-Script#110]
curl -c ./cookie -s -L "https://drive.google.com/uc?export=download&id=${fileid}" > /dev/null
curl -Lb ./cookie "https://drive.google.com/uc?export=download&confirm=`awk '/download/ {print $NF}' ./cookie`&id=${fileid}" -o ${filename}

**Comment by CardealRusso** [comment]
you can adapt this commands to php
i recommend streaming the out file to browser

**Comment by adeadw** [comment]
I still dont understand, so what do i need to make the script working again and bypassing the filedeo ? Can you please help me to better understand this
