### ISSUE TITLE
Stuck, Stream can't play video

### ISSUE THREAD

**Issue by akmaljp** [ArdiArtani/Google-Drive-Player-Script#111]
After deploying and seting gdrive api key, i try to add video. But the video won't play i dont know why, something wrong?
![image](https://user-images.githubusercontent.com/46837901/56465136-fba36a80-6421-11e9-83bc-70d47b98631d.png)

**Comment by ArdiArtani** [comment]
Problem Fixed https://github.com/ArdiArtani/Google-Drive-Player-Script/commit/c45287ce95755abb9ecaa5183208a0719fd224ae
