### ISSUE TITLE
Won't grab DL links for certain files

### ISSUE THREAD

**Issue by milankragujevic** [ArdiArtani/Google-Drive-Player-Script#12]
Try the script iwth https://drive.google.com/file/d/0B5qICdpK2azodGlwYngweGF3VzA/view ... It won't work...

**Comment by mbivol10** [comment]
Well if you noticed your video is actually missing the download button, while the video in the demo has a download button. My guess is you have restricted permissions or your account settings are messed up. Don't blame the API, it is doing what It can do given the proper account. So try it again once you fix the permissions issue.

**Comment by milankragujevic** [comment]
Try uploading a 700MB video and try it into the API it won't work, only videos less than 35 MB work...

**Comment by threathgfx** [comment]
@milankragujevic as @mbivol10 said, the permission is messed up, fix it since mine was working and this file sizes up to 3gb tho

![screenshot_74](https://user-images.githubusercontent.com/29234610/26998314-cde73b42-4db4-11e7-97b9-eb3d167f978d.png)

**Comment by milankragujevic** [comment]
ok.
