### ISSUE TITLE
how to hide/encrypt the video source in jwplayer?

### ISSUE THREAD

**Issue by kamran-tahir** [ArdiArtani/Google-Drive-Player-Script#13]
I am using your script and it is great. I just want to make my jwplayer video src secure so any one can not stream my video or copy my video source. I have searched a lot but no success. Is it possible?

**Comment by threathgfx** [comment]
You can modify the code, get a jwplayer code and edit some variables

**Comment by kamran-tahir** [comment]
is this the answer? no technical information,no logic .What kind of answer is this? edit variables? which variable? what to do? strange answer.!!

**Comment by ArdiArtani** [comment]
I just created a script you can download it here <a href="https://github.com/ArdiArtani/Hash-URL">https://github.com/ArdiArtani/Hash-URL</a>
