### ISSUE TITLE
How to toggle different resolution for the same video file on jwplayer.

### ISSUE THREAD

**Issue by kamran-tahir** [ArdiArtani/Google-Drive-Player-Script#15]
Hi, I just want to toggle different resolutions for the same file like on youtube.
This is what I mean
I have a file of 1080p and it is playing then I need to provide the toggle resolution options below then 1080 like 720p,480p,360p . I have been exploring this and I found that we have to provide different sources for each resolution but I think it can be done using the same file. I am working hard and tried so many things but still no success.
This is what I am doing
```
$file = '[{"type": "video/mp4", "label": "360p", "file": "test.mp4"}]';
$file2 = '[{"type": "video/mp4", "label": "480p", "file": "test.mp4"}]';
<script type="text/javascript">
		jwplayer("myElement").setup({
			playlist: [{
				"sources":<?php echo $file?>,
				
			},
			{
				"sources":<?php echo $file2?>,
				
			}],
			allowfullscreen: true,
			width: '100%',
			aspectratio: '16:9',
		});
	</script>
```
File is playing but not showing any resolution toggle option.any solution?

**Comment by catalinx3006** [comment]
change $file with this

**Comment by catalinx3006** [comment]
$file = '[{"type": "video/mp4", "label": "360p", "file": "'.$linkdown.'"}, {"type": "video/mp4", "label": "480p", "file": "'.$linkdown.'"}, {"type": "video/mp4", "label": "720p", "file": "'.$linkdown.'"}]';

**Comment by kamran-tahir** [comment]
@catalinx3006  thanks a lot for your solution. I have implemented it and now "HD" button is showing but no options for 360p,480p are showing and when i click on "HD" button video pause for a second and then play again. It is not toggling resolution.

![screen](https://user-images.githubusercontent.com/29511058/27516530-3e9a189c-59d5-11e7-8585-0297455d315a.png)

**Comment by chopraaa** [comment]
Because you need files of different resolutions to toggle between them...

**Comment by kamran-tahir** [comment]
can we do it using the same file. If i have 1080p file . jw player should toggle its resolution to lower resolutions.What you say is it possible?

**Comment by chopraaa** [comment]
This is not possible.

**Comment by kamran-tahir** [comment]
@chopraaa  can you provide me a reference of what you are talking about the "Fact"?any authentic and logical reference?

**Comment by chopraaa** [comment]
https://support.jwplayer.com/customer/portal/articles/1428524

**Comment by kamran-tahir** [comment]
Nice article thanks. what does this mean?Quality Toggle vs Multiple Sources

**Comment by milankragujevic** [comment]
@kamran-tahir You obviously don't understand how video works, but in any case, you need to have a different video file to be able to play it at a lower resolution. Google Drive transcodes the files so that you can watch even AVI (XVID) files in the browser because they transcode to MP4 (H.264+AAC), but if you're using direct download link that is not done and so it's not possible to watch lower resolution.
