### ISSUE TITLE
google photo video is not playing in jwplayer

### ISSUE THREAD

**Issue by kamran-tahir** [ArdiArtani/Google-Drive-Player-Script#16]
I uploaded my video in google photos and then try to play the link in jwplayer but it is not playing . is this "google-drive-player-script" can play the video from google photos with modification.?

**Comment by Leonsss** [comment]
@kamran-tahir I don't think that this script support video's url from google photo. But u can enable allow google photos in google drive option and take video url from google drive

**Comment by kamran-tahir** [comment]
@Leonsss  thanks for reply. how can I allow google photos option in google drive? can you elaborate a bit?

**Comment by Leonsss** [comment]
@kamran-tahir In your google drive u have a settings option. At the top of your right side. Click the settings icon and than u will see some options. Check the option ( Create a Google Photos folder , Automatically put your Google Photos into a folder in My Drive ). Then in your google drive u will see a folder named google photos. There u can find all videos from google photos. Note: the videos will appear only after they are fully encoded.

**Comment by kamran-tahir** [comment]
@Leonsss @ArdiArtani  any way to play it programmatically?

**Comment by Leonsss** [comment]
@kamran-tahir I didn't understand you. Can explain it a bit more

**Comment by ArdiArtani** [comment]
This repository is only for google drive

**Comment by ArdiArtani** [comment]
https://github.com/ArdiArtani/Google-Plus-Player-Script

**Comment by kamran-tahir** [comment]
Thanks a lot @ArdiArtani You are such a great person.

**Comment by VanChannak** [comment]
I cant find where I can embed to post?
How can I ?
