### ISSUE TITLE
it does not generate the redirector.googlevideo.com..

### ISSUE THREAD

**Issue by donguyenha** [ArdiArtani/Google-Drive-Player-Script#17]
i check the cached files in cache folder and the link is 
https://doc-08-7c-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/kkkkq0kcmslfojlfrlojiq058bpmf1e1/1498528800000/1340883420501142032

it is not redirector.googlevideo.com/videoplayback

how to fix it

**Comment by threathgfx** [comment]
@donguyenha, it really doesnt generate redirector.googlevideo.com. It only focuses to the direct download using `uc=`

**Comment by donguyenha** [comment]
@threathgfx how to generate the link with redirector.googlevideo,com, 
ex: 
https://redirector.googlevideo.com/videoplayback?id=49ce579a8ac5005b&itag=22&source=webdrive&requiressl=yes&ttl=transient&pl=33&ei=OnNTWeaMJpPIqAWgx5WoBg&mime=video/mp4&lmt=1498589208203180&ip=2600:3c01::f03c:91ff:fe60:c14e&ipbits=0&expire=1498655610&sparams=api,ei,expire,id,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pl,requiressl,source,ttl&signature=0E1E8B5519026E7AC7BDCB89C55F2A305B6D50B7.7657FCDC57659A4F06FB0C9A03E502539C79074C&api=B4D9C084A100269C74C2292DDF010&cms_redirect=yes&mm=31&mn=sn-n4v7sn7y&ms=au&mt=1498641098&mv=m&key=cms1&app=storage

**Comment by chopraaa** [comment]
That's currently being discussed as we don't know yet. Nobody has made it public if they do know.

**Comment by CB49** [comment]
except they have. refer to youtube-dl. its public
