### ISSUE TITLE
How can we use this in our site

### ISSUE THREAD

**Issue by freddiehdxd** [ArdiArtani/Google-Drive-Player-Script#18]
l mean everything work fine on the demo. how to make it work on a site with multiple google drive videos in my case more than 400 one in each post. can we the self host jwplayer with this?
is this a temporary solution or google will kept changing they method.

developer email me:

**Comment by ArdiArtani** [comment]
Download the files upload them and call the function for each google drive video.

**Comment by freddiehdxd** [comment]
How to call then?. What function? I am using WordPress

**Comment by freddiehdxd** [comment]
can we implement it in a jwplayer plugin ?

**Comment by freddiehdxd** [comment]
and how to use it with flowplayer

**Comment by ArdiArtani** [comment]
Thats something I can not help you.

**Comment by freddiehdxd** [comment]
but how can l call the videos?
