### ISSUE TITLE
Have new update ?

### ISSUE THREAD

**Issue by matamune15** [ArdiArtani/Google-Drive-Player-Script#2]
Hi , Have new update ? and how install it ?

**Comment by izay4kun** [comment]
I'm trying to figure out how to solve that too, so far i only found a website back-end api which generates an google video in a json output the url generated is:

> https:\/\/redirector.googlevideo.com\/videoplayback?requiressl=yes&id=e262a025b63fc415&itag=22&source=webdrive&ttl=transient&app=explorer&ip=2a02:5060:513:c049::2&ipbits=32&expire=1479836253&sparams=requiressl,id,itag,source,ttl,ip,ipbits,expire&signature=8DCD426BEAF5B898234271BB94169736CE73408A.2FF3C58CE4C5041C22BD56E640C7B57C7C141E79&key=ck2&mm=31&mn=sn-5hne6n7y&ms=au&mt=1479821764&mv=u&nh=IgpwcjAxLmFtczE2KgkxMjcuMC4wLjE&pl=32

(the differences between ArdiArtani output and this are the ip [obvious], the CP tag that don't exists on this code and the ipbits in ArdiArtani code has 0 as value this code above 32).

**Comment by matamune15** [comment]
wow , ipv4 can play ?

**Comment by matamune15** [comment]
here :
https://r4---sn-8pxuuxa-nbor.googlevideo.com/videoplayback?requiressl=yes&id=e262a025b63fc415&itag=22&source=webdrive&ttl=transient&app=explorer&ip=171.248.107.94&ipbits=32&expire=1479836253&sparams=expire,id,ip,ipbits,itag,mm,mn,ms,mv,pl,requiressl,source,ttl&signature=06B57C2F51A14D0082182ACD01FF43EF3D357288.32F5B57B391559D835A9D146D5FD39D999FCB0CB&key=cms1&pl=20&cms_redirect=yes&mm=31&mn=sn-8pxuuxa-nbor&ms=au&mt=1479835614&mv=m
, u can play this link ?

2016-11-23 0:29 GMT+07:00 box snow <svsnowbox4u@gmail.com>:

> wow , ipv4 can play ?
>
>

**Comment by ArdiArtani** [comment]
This issue is closed please check issue #3
