### ISSUE TITLE
How to hide/encrypt jwplayer ajax requests that contains the video id .

### ISSUE THREAD

**Issue by kamran-tahir** [ArdiArtani/Google-Drive-Player-Script#20]
Hi, I want to hide or encrypt the ajax calls send by jwplayer that contains the google video id and someone can steal this id to leach the video. Is there any way to hide/encrypt the ajax calls?

**Comment by kamran-tahir** [comment]
@ArdiArtani I need your help about this issue. I want to hide these id's (1i........3A_uw) in the ajax request.
<img width="1303" alt="ajax request" src="https://user-images.githubusercontent.com/29511058/27842527-3428ae72-6124-11e7-9e36-0b58b6ec30bf.png">

**Comment by milankragujevic** [comment]
@kamran-tahir You can't.

**Comment by chopraaa** [comment]
You can use a proxy script.

**Comment by kamran-tahir** [comment]
@chopraaa  would you please explain a bit about proxy script?

**Comment by kamran-tahir** [comment]
@ArdiArtani I need your help. i am waiting for your reply.

**Comment by ArdiArtani** [comment]
Duplicate issue, please checkout this closed issue https://github.com/ArdiArtani/Google-Drive-Player-Script/issues/13

**Comment by kamran-tahir** [comment]
@ArdiArtani  no it is totally different issue. Please read it . the #13 issue is about hide/encrypt video source not hide/encrypt google drive video id in ajax call. Both are totally different things. Please reopen the issue.

**Comment by kamran-tahir** [comment]
@ArdiArtani  do you have any soulution about this issue?

**Comment by ArdiArtani** [comment]
You can use this php function to encrypt your id.

```
<?php 
function my_simple_crypt( $string, $action = 'e' ) {
  $secret_key = 'drivekey';
  $secret_iv = 'google';
  $output = false;
  $encrypt_method = "AES-256-CBC";
  $key = hash( 'sha256', $secret_key );
  $iv = substr( hash( 'sha256', $secret_iv ), 0, 16 );
  if( $action == 'e' ) {
    $output = base64_encode( openssl_encrypt( $string, $encrypt_method, $key, 0, $iv ) );
  }else if( $action == 'd' ){
    $output = openssl_decrypt( base64_decode( $string ), $encrypt_method, $key, 0, $iv );
  }
  return $output;
}

// Encrypted Google Drive ID
$id = my_simple_crypt($_GET['id']);
// This will echo a random string. Example: NCtLVmJ0WjJEWUZCQkQ5Nk5qcFB6Zz09

// Decrypted Google Drive ID
$original_id = my_simple_crypt($id, 'd');
// This will echo your google drive id.
?>
```


Change _$secret_key_ & _$secret_iv_ to whatever you want.

**Comment by mangemve1511** [comment]
@ArdiArtani Can you write ajax function? Thanks.
