### ISSUE TITLE
Anyway to implement this script in Wordpress posts/pages

### ISSUE THREAD

**Issue by isjunked** [ArdiArtani/Google-Drive-Player-Script#21]
Hello,

Is there anyway to use this script with Wordpress. I tried to call the `curl_gd.php` by putting `include('wp-content/themes/themesfolder/curl_gd.php') ` into `functions.php`. Also used a plugin called Insert PHP and inserted these text into a Wordpress post. (I want to create one post per video)

```
[insert_php]
        include('wp-content/themes/themesfolder/curl_gd.php');
	$url = "https://drive.google.com/file/d/************************/view";
	$linkdown = Drive($url);
	$file = '[{"type": "video/mp4", "label": "HD", "file": "'.$linkdown.'"}]';
[/insert_php]
<style>
		.container {
		  max-width: 800px;
		  margin: 0 auto;
		}
	</style>

	<div class="container">
		<div id="myElement">Video loading.</div>
	</div>
	<script type="text/javascript">
                alert ('<?php echo $linkdown?>');
		jwplayer("myElement").setup({
			playlist: [{
				"sources":<?php echo $file?>
			}],
			allowfullscreen: true,
			width: '100%',
			aspectratio: '16:9',
		});
	</script>
```

However the post didn't display any thing and my post page had a broken design. Ran it with the default `index.php ` and everything was ok. Can someone please tell me how to make this script work with Wordpress? Many thanks.

**Comment by chopraaa** [comment]
It'd be better if you made a plugin and called the script using a short code.
 `[drive]0xDsvouRRtYiSvEiETwYWj1bRLtm[/drive]` seems like a much better implementation to me.

**Comment by isjunked** [comment]
Thanks. I was thinking of creating a simple plugin with an input field in the Post Editor for the link, similar to your solution. However I'm not a programmer and I can't figure it out how to create the input field, deliver the value to the script by submitting then get the result displayed automatically . Could you please tell me what do I need to do to achive the result? I'm willing to learn. And can you please explain why this script can't be used for a high traffic site?

**Comment by jongcs** [comment]
You can embed the video player in your wordpress post.
For example:

example.php
```
<?php
error_reporting(0);
include "curl_gd.php";

if($_GET['drivelink'] != ""){
	$url = $_GET['drivelink'];
	$linkdown = Drive($url);
	$file = '[{"type": "video/mp4", "label": "HD", "file": "'.$linkdown.'"}]';
} 
?>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
<div id="player"></div>

<script type="text/javascript" src="https://ssl.p.jwpcdn.com/player/v/7.10.7/jwplayer.js"></script>
<script type="text/javascript">jwplayer.key = "rqQQ9nLfWs+4Fl37jqVWGp6N8e2Z0WldRIKhFg==";</script>
<style type="text/css">*{margin:0;padding:0}#player{position:absolute;width:100%!important;height:100%!important}</style>
<script type="text/javascript">
		jwplayer("player").setup({
			sources: <?php echo $file; ?>,
			allowfullscreen: true,
			width: '100%',
			height: "100%",
			aspectratio: '16:9',
		});
</script>
```
And put these html code in your post:
```
<iframe src="https://yourdomain.com/example.php?drivelink=https://drive.google.com/file/d/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/view" width="640" height="360" frameborder="0" scrolling="no" allowfullscreen></iframe>
```

**Comment by waqasbelushi** [comment]
Thanx  jongcs

**Comment by waqasbelushi** [comment]
I need Some More Help If i want To hide My Iframe Url What Can I Do.

**Comment by isjunked** [comment]
Thank you jongcs 👍

**Comment by milankragujevic** [comment]
@waqasbelushi You can encrypt the URL, contact me via email for details, milankragujevic@gmail.com .

**Comment by threathgfx** [comment]
You want something like this script?
`http://japnime.com/videotest/2017/07/09/koe-no-katachi/`

**Comment by localhazard** [comment]
@threathgfx interested your script, please contact me imansauqy@gmail.com imansauqy@gmail.com

**Comment by mangemve1511** [comment]
@threathgfx Can you share me that script?

**Comment by threathgfx** [comment]
@localhazard @mangemve1511  just mail me here: threathgfx@gmail.com

**Comment by mangemve1511** [comment]
@threathgfx I sented email to you.

**Comment by FosterG4** [comment]
Thanks It Work
