### ISSUE TITLE
Mozzila cant play it? eror media loading.

### ISSUE THREAD

**Issue by HandrianD** [ArdiArtani/Google-Drive-Player-Script#22]
https://drive.google.com/file/d/0B7_M_N3zWT51R1RiaTRFdlVhejQ/view
cant play event i use mozilla in other its work ty for nice script.
other il make it same not work on mozilla
https://gamerse.net/watch.php?vid=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8wQjdrQnpaY3huWE91ZVhRMmNHZFpVVTB0WTFVL3ZpZXc=&subs=&img=VHN1Z3Vtb21vLUVwaXNvZGUtMDItU3VidGl0bGUtSW5kb25lc2lhLmpwZw==

**Comment by ArdiArtani** [comment]
This script is still under development, the one you are using is temporary. Please wait for new updates

**Comment by pathboot** [comment]
i have fix this probleme, you need to upload a mp4 file this probleme come with .avi and .mkv , but with mp4 its working fine so you need to upload mp4 video not avi not mkv
