### ISSUE TITLE
İt has limitation

### ISSUE THREAD

**Issue by victornewman** [ArdiArtani/Google-Drive-Player-Script#23]
Today i figure out (after 6 hours spending) it has google drive limitation I think 40-50 times watch it enought to get limit error. You do not need script for this 1h3 link can be taken in gdrive account by right click and inspect page. But it has limit too.

Demo link turn to get link page, so you shoul know this isue.
We (I) need redirector.googlevideo.com link without 403 eror and limit problem.
Please guys if you know what is tge problem of your code mention about it by hiding you cause to kill others time for nothing.

**Comment by chopraaa** [comment]
By not reading other active issues, you're killing our time by making us read this.

**Comment by ArdiArtani** [comment]
#7
