### ISSUE TITLE
No audio in .mkv videos

### ISSUE THREAD

**Issue by xaiborweb** [ArdiArtani/Google-Drive-Player-Script#25]
Hello this is very interesting your script and I would like to support you with a grain of sand but all my videos are .mkv and I do not deliver audio to these videos, can you solve it?
example 
https://drive.google.com/file/d/0B9WqEghYLgCmeEVxNDlLVHZiUFE/view

**Comment by Nottt** [comment]
That's weird. I have mkv files too and they play just fine on google drive. Check with mkvtoolnix if there is a default audio set.

**Comment by caianjj** [comment]
Browsers don't support mkv, this has nothing to do with the script. I suggest you use mp4 files.

**Comment by ArdiArtani** [comment]
The script scrapes from the download page mkv doesnt work im still working on it to solve the quality problem.


On Aug 1, 2017 at 2:57 PM, <caianjj<mailto:notifications@github.com>> wrote:


Browsers don't support mkv, this has nothing to do with the script. I suggest you use mp4 files.
