### ISSUE TITLE
it's die 

### ISSUE THREAD

**Issue by dinhtienduc** [ArdiArtani/Google-Drive-Player-Script#27]
i try play with your demo, url https://drive.google.com/file/d/0B2BRsRdCsaKwWmlUZTAzZGFaQlE/view?usp=sharing but it's die 
please help me! thank you very much

**Comment by caianjj** [comment]
It's not a valid mp4 file.

**Comment by dinhtienduc** [comment]
the first, thanks for your request!
i think it is a mp4 file ,you can see my picture
)
![nono](https://user-images.githubusercontent.com/25727152/28874087-866a284e-77ba-11e7-8159-8ae30ab8ebbf.png)

**Comment by dinhtienduc** [comment]
i try with url :https://drive.google.com/file/d/0B4fU5__VXkIkTV9Zc0ozN2pzRlk/view?usp=sharing 
it's ok but i try with url : https://drive.google.com/file/d/0B2BRsRdCsaKwWmlUZTAzZGFaQlE/view?usp=sharing 
it's die .pls you can tell me why?

**Comment by michellewuu69** [comment]
this script is die?

**Comment by haxunivil** [comment]
Simple and reliable script for generating HTML5 video streaming links from Google Drive files.
it's not a proxy script, provide links direct to Google’s Video CDN
Easy Installation, You just need PHP hosting and Google Cloud PHP App account thats all, now you are ready to fly.
It's work with all public google drive videos on free and gsuite accounts.

Buy Google Drive Stream Links Script and TEST IT:
https://google.driveplayer.stream/

**Comment by zeydhan** [comment]
Hello, if you're looking for gdrive player that return lh3.googleusercontents link, please go to : www.gdriveplayer.us

plugin and API documentation is available there

Basically, here's how to use : http://gdriveplayer.us/embed2.php?link={insert link drive here}

Good luck
