### ISSUE TITLE
403. That’s an error.

### ISSUE THREAD

**Issue by jqw1992** [ArdiArtani/Google-Drive-Player-Script#3]
403. That’s an error.

Your client does not have permission to get URL /videoplayback?requiressl=yes&id=656517bf07b54306&itag=18&source=webdrive&ttl=transient&app=texmex&ip=192.210.151.102&ipbits=0&expire=1483121507&cp=QVJNVUJfUFVOSFhNOk1jMFBKT0NkMG52&sparams=requiressl%2Cid%2Citag%2Csource%2Cttl%2Cip%2Cipbits%2Cexpire%2Ccp&signature=33CBE7BAE89C46A49B2EADD4D784AA35D74111D4.3395D82F2653C565BE3BF2E12060C96191D71327&key=ck2&mm=30&mn=sn-4g5e6nl7&ms=nxu&mt=1483107024&mv=m&nh=IgpwcjAxLmZyYTE2KgkxMjcuMC4wLjE&pl=47&sc=yes from this server. That’s all we know.

**Comment by kishorkurian123** [comment]
Been working on it, but cant seem to find a working solution yet. I tried fetching the FMT stream map, and replace the encoded part to get the url, but that still gives me a 403.

If you want to work together, I can give you a working link that one of my friend has. I am not sure how he still gets the link though.

**Comment by ArdiArtani** [comment]
@kishorkurian123 Okay let me take a look at the script.

**Comment by cristiantimar** [comment]
I made the solution for the redirectors: you can check my site: https://apimov.com/

**Comment by ArdiArtani** [comment]
@cristiantimar Really nice script, I think I'm getting close to fix 403 error.

**Comment by cristiantimar** [comment]
Thanks. Google makes things very difficult this time :(.

**Comment by ArdiArtani** [comment]
@cristiantimar Can you send me your googe drive getlink script I want to take a look at it

**Comment by kishorkurian123** [comment]
Can you guys drop me your email? @ArdiArtani  @ArdiArtani

**Comment by ombapit** [comment]
@cristiantimar  wow perfect, can u share the code for public?
thanks.

**Comment by dunglt** [comment]
I tried to use apimov.com with my movie :( but it doesn't work 
This is my link : https://apimov.com/get/0Byg7tNWXYRqkcl9TX01hcmZMTXM
403 :( . Please help me

**Comment by dunglt** [comment]
May be my extensions file is .mov . Let me check with mp4 .

**Comment by cristiantimar** [comment]
@ArdiArtani Sorry. I cannot share the code.
@dunglt I checked the url and the redirectors works. Decode urls before access them.

**Comment by dunglt** [comment]
It doesn't work . I use this link in your tutorial in webapi  @cristiantimar 
![capture](https://cloud.githubusercontent.com/assets/2187186/26543829/a9bf7fc4-4489-11e7-9f63-743b38d882a6.PNG)
![capture1](https://cloud.githubusercontent.com/assets/2187186/26543830/a9c0b916-4489-11e7-8a3e-0d01c9b9bc6a.PNG)

**Comment by cristiantimar** [comment]
Use http://json.parser.online.fr/ to decode json. Apimov returns json results. So it is not decoded.

**Comment by dunglt** [comment]
@cristiantimar : the result is the same , this link sample in your website doesn't work with me . I parse the result and get only the "https:\/\/redirector.googlevideo.com\/videoplayback?id=3d6e61d65f9455ef&itag=18&source=webdrive&requiressl=yes&ttl=transient&mm=30&mn=sn-5hne6nl7&ms=nxu&mv=u&pl=22&ei=lN8rWZXCMtjXqQWMgKzQAg&driveid=0Byg7tNWXYRqkcl9TX01hcmZMTXM&mime=video\/mp4&lmt=1495678485072044&mt=1496047256&ip=179.43.183.98&ipbits=0&expire=1496061908&sparams=ip,ipbits,expire,id,itag,source,requiressl,ttl,mm,mn,ms,mv,pl,ei,driveid,mime,lmt&signature=334F43705534B583EC822DCB03CF5A1A9AB7640F.17E52CE8A57935C7327372C66905747104E256AD&key=ck2&app=explorer" . 
Cannot work :( :(

**Comment by cristiantimar** [comment]
Something wrong from your side: this redirector works: http://prntscr.com/fdbi95

**Comment by nattatorn-dev** [comment]
@cristiantimar Thank for very good api. it's work for me (type .mp4)

**Comment by dunglt** [comment]
@cristiantimar  : I know my error . Thanks a lots . Sorry for my stupid .

**Comment by dunglt** [comment]
@ArdiArtani : I hope you can fix this 403 error soon . I believe in you . 
Thanks for your sharing

**Comment by nattatorn-dev** [comment]
@ArdiArtani I will try to find a solution together.

**Comment by kishorkurian123** [comment]
@cristiantimar - Atleast you could give us some pointers to guide us in the right direction. Fellow developers here :)

**Comment by ArdiArtani** [comment]
My email is: ardiartani@gmail.com

**Comment by kishorkurian123** [comment]
@cristiantimar  - I can add in a $100 if that helps ha ha. Just to letting me know how to do it in the right way. :) My email is kishorkurian123@gmail.com Offer open to anyone :) 

Fellow coder looking to get some help :)

**Comment by asnawibato** [comment]
So how to embed it in jwplayer to stream the videos?

**Comment by mangemve1511** [comment]
@ArdiArtani Waiting you fix error 403. Just doneted some money. :) Email: hungvo.pjh@gmail.com

**Comment by mkalyon** [comment]
@ArdiArtani, did my mail receive?

**Comment by ArdiArtani** [comment]
@mangemve1511 Thank you. @mkalyon What's your email address ?

**Comment by Sweeeeep** [comment]
@ArdiArtani did you already fix the 403 issue ? if you fix it i will donate too 👍

**Comment by dunglt** [comment]
@ArdiArtani  : I will  donate too . See your code soon

**Comment by ArdiArtani** [comment]
@Sweeeeep @dunglt Hey guys I'm trying but can't find a solution but I did manage to get only 1 working streaming link, you can check the demo [here](https://www.filedeo.com/views/gd/status.php) if you want me to publish the script let me know.

**Comment by mkalyon** [comment]
Maybe This helps you.
http://dmdsoftware.net/

**Comment by dunglt** [comment]
@ArdiArtani  : please share with me . My email : dunglt@bkindex.com . 
Thank for your distribute

**Comment by arlondalief** [comment]
@ArdiArtani can i get the script from https://www.filedeo.com/views/gd/status.php it's work for me.
 my email : pushplay@std.unissula.ac.id thx

**Comment by Sweeeeep** [comment]
@ArdiArtani Please publish that script :) seems its working

**Comment by ArdiArtani** [comment]
I'm uploading the files right now.

**Comment by ArdiArtani** [comment]
@mkalyon I'm going to take a look at the code. Thanks

**Comment by ArdiArtani** [comment]
The files are uploaded.

**Comment by ombapit** [comment]
403 errors because url get_video_info requires login to google.
Please try my step:
1. Login to google via firefox
2. After login, run this link for ex: http://drive.google.com/get_video_info?docid=0B2Xl2dXzKE5NT2JmMVFuNm5CSGM
3. decode first fmt_stream_map: https://prnt.sc/fqzbq0
4. run the url decode in url in firefox
5. In my case, generated link is worked.

I think solution for this 403 errors  is make php login to google via curl. After that, we can try http://drive.google.com/get_video_info?docid=
What i still cant is login to google via curl. If Anyone can succeded login to google, please reply my post.
thanks.
