### ISSUE TITLE
Stream video from google photo

### ISSUE THREAD

**Issue by alamgircsejnu** [ArdiArtani/Google-Drive-Player-Script#30]
Hi. Thank you for this nice script. This script helped me very much. I need another help from you. I also need to stream video from google photos. The structure of video url from google photo is 
https://photos.google.com/share/AF1QipNcJG9nvepx-KkxXcpMClaLfvOktMInISXx5_swiiqvbYcnopkSZ6uvzw_q4FiJRA/photo/AF1QipMAZr3XfsKUHyOpylqW52dfU0lmdAyrSyetaWz2?key=TEhFTXF3SllBQkJDYVhEaE1vRktBZi05MkhqZnhn

I trying to get direct link from this link but failed. The direct link pattern is
https://lh3.googleusercontent.com/9aFqeouYX2oicneZXBIq8LgNEP7Kg3ERCWsA3DZvgGaXd1bI3uikJhTik0vybmKxBQ6mUANFTyfabsc_7igu31E5i9HcjdaCh_6OWlbuxVOaN2uDJE5AB85qLj43q-qONkKeGtGnog=m18

Please help me. I am stuck with this problem.

**Comment by caianjj** [comment]
[https://github.com/ArdiArtani/Photo-Google-Player-Script](https://github.com/ArdiArtani/Photo-Google-Player-Script)

**Comment by alamgircsejnu** [comment]
Thank you very much for your quick response but the script is showing error. I have attached a screenshot of the error. Can you check it for me please?
![capture](https://user-images.githubusercontent.com/19221035/29100414-2eaff170-7ccd-11e7-9d92-ce6977029328.PNG)

**Comment by threathgfx** [comment]
This will not work at local servers, I dont know why but when you insert this from any free webhosting, it will work

**Comment by caianjj** [comment]
it works for me

**Comment by ArdiArtani** [comment]
https://github.com/ArdiArtani/Photo-Google-Player-Script
