### ISSUE TITLE
Blogspot Streaming

### ISSUE THREAD

**Issue by monster1777** [ArdiArtani/Google-Drive-Player-Script#31]
Did you see the new way of streaming videos? Some sites use 3.bp.blogspot.com domain instead of redirector.googlevideo.com. Has anyone looked into it as how it is done?

**Comment by threathgfx** [comment]
Yeaah, i've seen this like in 9anime

**Comment by caianjj** [comment]
fmovies.is and gostream.is are also using it. 3.pb.blogspot.com is the same as lh3.googleusercontent.com

**Comment by monster1777** [comment]
Isn't lh3.googleusercontent.com from google photos? Is there any upload api / upload limit to google photo, or can I use it as a storage/streaming place?
But yeah, that blogspot is interesting, I wonder how they get that links, don't think that they upload videos to blogspot because it has 100mb limit

**Comment by monster1777** [comment]
Okay yep seriously lh3 is same as that 3.bp, I have https://lh3.googleusercontent.com/oIW4XQdyRs2oswIIRO_PSYO4LzGPdLtSaXqrk2oDOs9KtvZaZdwdcYVYIV62R5tl62ORRyC00L15yJietKNurgZFHsuneeaH56ABZeQ8Nj0whtnxqWdjpiEhEHeC9NzWVmqNQ37BTQ=m18 this link, just change lh3.googleusercontent.com to 3.bp.blogspot.com and works.
Now lh3 is google photos, is there any api for it for mass upload that some of you may know of?

**Comment by caianjj** [comment]
lh3 is from google photos yes.

> is there any API for it for mass upload that some of you may know of?

I don't know

This is a link from fmovies.is 
`https://3.bp.blogspot.com/-yUmllT8C1RAFv028AdghlBpM-pNzcD-G7bpl4P9ffscUdDsVOL8SyehJu5R2EnEDwSaf9sdsg=m22?s=Zw7T0o1fS/BN646D04rEYE7EmYRsgqsF/A7HgvENmA0dkoc=`

and it redirects to
`https://r1---sn-5hne6nlr.c.drive.google.com/videoplayback?id=144976684f2b9c21&itag=22&source=webdrive&begin=0&requiressl=yes&mm=30&mn=sn-5hne6nlr&ms=nxu&mv=u&pl=44&sc=yes&ei=NGyMWdOeJcqJ1gK3x66ABQ&susci=o-ADaU2UsEVinShrJ8NsvSr68dV4-mwp2wcNn7duh_8U2cj8Br&driveid=0ByeqM4EKt405V3JobGstOURNaU0&mime=video/mp4&lmt=1502346827754698&mt=1502374787&ip=2001:985:2a98:1:2408:81e5:787d:9a0f&ipbits=48&expire=1502382164&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mn,ms,mv,pl,sc,ei,susci,driveid,mime,lmt&signature=AD8ADF71C85B3823252C632CE96D7816983DDF92.4D04EDD87E9BE19CF8F693FEA67B4874400BCBEB&key=ck2&s=Zw7T0o1fS/BN646D04rEYE7EmYRsgqsF/A7HgvENmA0dkoc=`

In the link, you see `source=webdrive` which is weird since the link is `3.bp.blogspot.com` and if the video really is from blogspot it would be `source=blogger`

**Comment by caianjj** [comment]
well... [http://yellowartz.nl/test/](http://yellowartz.nl/test/)

**Comment by monster1777** [comment]
Well yep I've seen that gomovies (gostream) has source=webdrive too. I only managed to do that with google photos, simply getting the lh3 link and replacing it with 3.bp.blogspot.com and it works, but shows source=picasa. Still can't manage to get that blogspot link for drive. Also what I can see that the 3.bp.blogspot.com links that redirects to webdrive are shorter, while those redirecting to a video on google photos is longer

**Comment by caianjj** [comment]
I found out how to create a link with `source=webdrive` but I don't think this is how gostream.is is doing it.
It Goes as follows

1. Upload a video to google drive
2. Go to google photos
3. Then go to settings and check this box 
![image](https://user-images.githubusercontent.com/22570868/29192924-9514d37a-7e23-11e7-9722-722093cea14c.png)
4. You will see the video from google drive in your google photos library
5. Share the file and get the `lh3.googleusercontent.com` from the source.

And that's it the redirector will redirect you to the `source=webdrive` link.

Here's a demo: [http://yellowartz.nl/test/](http://yellowartz.nl/test/)

**Comment by monster1777** [comment]
Yup your method works.
One thing I noticed - my links don't die, and the ones from gomovies and others die after about 12 or 24 hours. So they must be using some other method.

**Comment by milankragujevic** [comment]
I think the key might be to share a drive link on Blogger, like making a blog post and embedding a Drive link in it, but I'm not sure how because if I embed drive it just uses an iframe or on old Blogger it just displays 240p FLV video...

**Comment by RiseCoder** [comment]
Drive + All Qualifications + Open Source + Magnificent Player System Only 300 TL

Demo: http://drive.rangeplayer.com/

User Name: admin
Password: demo

**Comment by RiseCoder** [comment]
Drive + All Qualifications + Open Source + Magnificent Player System Only 300 TL

Demo: http://driver.rangeplayer.com/

User Name: admin
Password: demo

**Comment by threathgfx** [comment]
Did 1080p got blocked?
`http://japnime.com/_new/download.php?id=MzEwMzce`

**Comment by threathgfx** [comment]
it seems like the shorter string came from this `https://get.google.com/albumarchive/`
Is it possible to public that links there?

**Comment by RiseCoder** [comment]
Google Drive and Other Platform Player Api Service

Fast, secure, fixed price guarantee.

Supports: Google Drive, Google Photos, Youtube, Vimeo, Vid.me, Dropbox

Demo: http://www.playersapi.com

Our API currently costs roughly $1 per 1,000 requests. Requests for the same link within an day are not charged.

Skype : api@playersapi.com

**Comment by Zebraslive** [comment]
You can also get the link like this
```php
<?php

$file = file_get_contents('https://photos.google.com/share/AF1QipPcN6fc8RbBzMF51jSYvVAZPB5KgRQUvPmlVlacxTrJkKleZ904mqagxxp9F9yp7Q/photo/AF1QipM8LMCeDxoF3wwcFWFJtFFWzStqBOwpTiQ3pzq2?key=M2dEVVRrQXFmZ3VCVjczcXFWaF8wZjJWUzF6WE93');

$dom = new DOMDocument();

@$dom->loadHTML($file);
$count = 0;

foreach($dom->getElementsByTagName('script') as $js) {
    
    if ($count === 14 || $count > 14) {
    
        echo $js->nodeValue;
        echo "<br />"; 
    }
    $count++;
    
}
?>
```
if you parse that script tag you can get this direct download link as well as thumbnail img and resolution urls but I can't figure out how to use them.
This link works tho. if it helps anyone....let me know if you figure out something.
https://video-downloads.googleusercontent.com/APJDyBp8tUscPtD6hcwp25UEI72orESaswUjbOGEPKiWqhTlgqlUEQtK3QLs-nv3keVvUNZ94y3gvykyEb1FlcG6pbaa5FOEFNo8yjnyX4rDu9IpUAda57vxJWpLazVJoK26hw6Q1UcnvvxJlkSW32--OtghynAehcgAmsq_3juhKL5zTXSIEvSfCMe4cNlF2Pcas-QtJfnA8xi5Z0sHS3DIvGZe7PQ6B1VXDj0cg_z84ADjTnOYndiiPYZDuyaTVG2JNUQ1osGWKR-IT3OmnxiXrS1znsuR2tlWm6F8ew3-cw82oh5swJciOh0bYaiwBMuDd3C6UU3adIuw3kKUQwVbfbzwE5cmcz46fnuuXkhwlDfWObJrgw3CaOkYfEdWs7xewCkqXDXz-C_gLangfPxs3jEZWLjVydn4WpsoZi9T7KPKY4eaabPTiWK8a9yhy6dA6TAhSCUbMIgeHXyWgP_MHZg-R0urb2-LilYlZyn0t8nQqOC4lWLaBdpXNxGj07f7xxmqIy0XGY8czStuDKcNXiDscaGi1F-JTpALjWtXd293_isrCAFfH92g4pLf3_cPIpnZtfgvJPJJ3irJLPa4sOtMU1p_D7GJj7s8L7djFP746zbpXmxPzr1vf1wIH2x2HpnXBhL--sPFyMQN5ytSwZ6QH5j1j2cwDUzc3TVEtqhaNiMAGB2WvzuumubDZn92RWjX6AlbdW2rwN4aY5FnNkOLHg9251nX-vBbubrgLC-oHQ5pYebIjxBvrkdIHjnWoPD_J24vtnnjERKxAtb-_KXGFQYpMS9K2BW-xybc2jDrUAQGGGo

**Comment by threathgfx** [comment]
@Zebraslive let me cheeck

**Comment by monster1777** [comment]
Now big streaming sites use links like this: https://storage.googleapis.com/visit-dupleplaycom.appspot.com/freemovies/cj7nax1bi0405n7sduxnd0s1v.mp4 how?

**Comment by hklcf** [comment]
@monster1777 http://dupleplay.com/

**Comment by Zebraslive** [comment]
@monster1777 @hklcf Yes but that would mean that company is selling storage using google cloud and they wouldn't ignore dmca......... it can't be stable. Although it's a tempting price.

**Comment by monster1777** [comment]
The prices are reasonable given how much a video streaming site earns. I considered buying it, but I think I will just "borrow" the links from gomovies.

**Comment by dungvaph03374** [comment]
@monster1777 omg did you notice that the link you posted still working?

**Comment by aalfiann** [comment]
unfortunately, i've been make a test using google photos, link share is working on the past, but after few days, the source video got http status 429 or limited.

**Comment by dungvaph03374** [comment]
better use facebook bro!
remote upload via api, public link anyone can view, no limit, is there anywhere to host your video better than facebook?

**Comment by khalisafkari** [comment]
@Zebraslive error get data 

`<?php

$file = file_get_contents('https://photos.google.com/share/AF1QipMTEPAiVF8t0YqLukflnOSQjwfd8ARIoT2h37AXvYO1uaWodbeiFoBUDuD_19tEbg/photo/AF1QipPA2Bq0JlAR9LoGD3mogsxSb9OZWEG4XqBDD4Rv?key=cjhUT0xrZjM5NGN2SVRLOVptZU5SMUlKV0lQYWpB');

$dom = new DOMDocument();
@$dom->loadHTML($file);
$count = 0;

foreach($dom->getElementsByTagName('script') as $js) {
    
    if ($count === 14 || $count > 14) {
    
        echo $js->nodeValue;
        echo ""; 
    }
    $count++;
    
}
?>`

Result

AF_initDataCallback({key: 'ds:1', isError: false , hash: '1', data:function(){return [["AF1QipPA2Bq0JlAR9LoGD3mogsxSb9OZWEG4XqBDD4Rv",["https://lh3.googleusercontent.com/9hjfn7zqOZINb2UmY352yVU3XWLE7vvtDRHiWm9KPwd6hIBultO5yFea0yzGkwNdci9c-Y1SJINEN6dqoqrTqFI2B57d9Di_tODQ2Tsrp0nXS9XCfU9nCvxp1ONbQoquLFeeesa3iw",1920,1080,null,null,null,null,null,null,[3289650] ] ,1472301124000,"btrC7xbRUmW7GAcMFu2ZdYWewqo",-14400000,1499698463648,["AF1QipPT-j9MGHbFou_ZffW8ygEf_htQ"] ,[[2] ,[8] ,[21] ,[19] ,[22] ] ,2,null,null,null,{"76647426":[5296,true,1920,1080] }] ,"https://video-downloads.googleusercontent.com/AK2sVMiSzukkFa0LdacGzSaXOfdlNKGUTdjCGpItulDFMMu4M85ejcxCo__x8aqeZE_SYvBerEqAFWiZhZvzzq45kJ6VDyCpebv1B5pc3h5_xus3if8qubjx7_zkZHv-EqGN3ZIJdHvlSV4LtGed_BuNeymjzzPxIiuaHhU3OaQctsg-SzyHpbw",[[2] ,[8] ,[21] ,[19] ,[22] ] ,["AF1QipPT-j9MGHbFou_ZffW8ygEf_htQ","108121785305577210572","Ardi Artani","https://lh3.googleusercontent.com/yql3zR9NA9lgBjDZ6xwdh3JQZWcJfAAKmJiXu4eV0jAigFfN6G6wAz6VR4Y0TF9ipUtMhzyKLcFZZb71qcGTcA3GJF06eGBCUIJYWjIUKSg",null,["AF1QipPT-j9MGHbFou_ZffW8ygEf_htQ","108121785305577210572"] ,null,null,null,null,null,null,["https://lh3.googleusercontent.com/a/AD4M7oxQpf92TnaqaoofW6mEFcRccZdOOaeMJMUq8imM"] ,null,null,null,null,[2] ] ,null,null,null,null,null,null,"",{"79468658":[[[5.296,"37/1920x1080,22/1280x720,18/640x360,36/320x180","url\u003dhttps%3A%2F%2Flh3.googleusercontent.com%2F9hjfn7zqOZINb2UmY352yVU3XWLE7vvtDRHiWm9KPwd6hIBultO5yFea0yzGkwNdci9c-Y1SJINEN6dqoqrTqFI2B57d9Di_tODQ2Tsrp0nXS9XCfU9nCvxp1ONbQoquLFeeesa3iw%3Dm37\u0026itag\u003d37\u0026type\u003dvideo%2Fmp4%3B+codecs%3D%22avc1.64001F%2C+mp4a.40.2%22\u0026quality\u003dhd1080,url\u003dhttps%3A%2F%2Flh3.googleusercontent.com%2F9hjfn7zqOZINb2UmY352yVU3XWLE7vvtDRHiWm9KPwd6hIBultO5yFea0yzGkwNdci9c-Y1SJINEN6dqoqrTqFI2B57d9Di_tODQ2Tsrp0nXS9XCfU9nCvxp1ONbQoquLFeeesa3iw%3Dm22\u0026itag\u003d22\u0026type\u003dvideo%2Fmp4%3B+codecs%3D%22avc1.64001F%2C+mp4a.40.2%22\u0026quality\u003dhd720,url\u003dhttps%3A%2F%2Flh3.googleusercontent.com%2F9hjfn7zqOZINb2UmY352yVU3XWLE7vvtDRHiWm9KPwd6hIBultO5yFea0yzGkwNdci9c-Y1SJINEN6dqoqrTqFI2B57d9Di_tODQ2Tsrp0nXS9XCfU9nCvxp1ONbQoquLFeeesa3iw%3Dm18\u0026itag\u003d18\u0026type\u003dvideo%2Fmp4%3B+codecs%3D%22avc1.42001E%2C+mp4a.40.2%22\u0026quality\u003dmedium,url\u003dhttps%3A%2F%2Flh3.googleusercontent.com%2F9hjfn7zqOZINb2UmY352yVU3XWLE7vvtDRHiWm9KPwd6hIBultO5yFea0yzGkwNdci9c-Y1SJINEN6dqoqrTqFI2B57d9Di_tODQ2Tsrp0nXS9XCfU9nCvxp1ONbQoquLFeeesa3iw%3Dm36\u0026itag\u003d36\u0026type\u003dvideo%2F3gpp%3B+codecs%3D%22mp4v.20.3%2C+mp4a.40.2%22\u0026quality\u003dsmall"] ,1920,1080] ] }] }});AF_initDataCallback({key: 'ds:0', isError: false , hash: '2', data:function(){return [null,null,0,null,"AF1QipMTEPAiVF8t0YqLukflnOSQjwfd8ARIoT2h37AXvYO1uaWodbeiFoBUDuD_19tEbg"] }});window.wiz_progress&&window.wiz_progress(); ccTick('bl');

**Comment by karimrafique** [comment]
Great post.
<a href="http://www.apkstub.com/2017/10/google-drive.html">Google drive</a>

**Comment by haxunivil** [comment]
[Sell] New Method to stream google drive videos for $100

Simple and reliable script for generating HTML5 video streaming links from Google Drive files. 
it's not a proxy script, provide links direct to Google’s Video CDN
Easy Installation, You just need PHP hosting and Google Cloud PHP App account thats all, now you are ready to fly. 
It's work with all public google drive videos on free and gsuite accounts.

Buy Google Drive Stream Links Script and TEST IT:
https://google.driveplayer.stream/

**Comment by voirvf** [comment]
Regarder Et Telecharger Des Films Online Gratuit sur VoirVF.com

http://voirvf.com
Le Meilleur Site Pour Regarder Gratuitement un maximum de film en streaming Complet sur VoirVf.Com

https://youtu.be/fctO2Pf9qsM

**Comment by ueja32** [comment]
[SELL] Google Drive Direct Links NEW METHOD!!!!
Simple and reliable script for generating HTML5 video streaming links from Google Drive files. 
it's not a proxy script, provide links direct to Google's Video CDN
Easy Installation, You just need PHP hosting and Google Cloud PHP App account thats all, now you are ready to fly. 
It's work with all public google drive videos on free and gsuite accounts.

DEMO AND MORE INFO: https://google.driveplayer.stream/

**Comment by CB49** [comment]
I felt like contributing to this, but I don't know if this was already known. What I found was that `1.bp` and `2.bp` work, along with `lh3` through `lh6`. 

Another interesting thing to note is that if you change the very last part of it, the `m[number]` part of it to `m15`, it gives you another image file displaying an error or something. It's longer and still works the same, just after changing the end of it back to `m22` or `m59`. Only applies to videos from drive, though.

**Comment by zeydhan** [comment]
Hello, if you're looking for gdrive player that return lh3.googleusercontents link, please go to : www.gdriveplayer.us

plugin and API documentation is available there

Basically, here's how to use : http://gdriveplayer.us/embed2.php?link={insert link drive here}

Good luck

**Comment by togetherguan** [comment]
Hi,for who need create video streaming link like this add my wechat,yaukimguan0219

Link Example
https://lh3.googleusercontent.com/cJJ6BrhYJaxMfRtwSRiBXYSBWgTyPkFbkJGf7bGJAZZt4WQR5r7MxhE-fzvxQbcKqLIXJEV_EhlDIw=m22?cpn=pLI5algSL5q1tVSp&c=WEB_EMBEDDED_PLAYER&cver=20180104.mp4

**Comment by CB49** [comment]
@togetherguan did u copy that link from somewhere else, or do u not understand how googleusercontent links work? cause half of that link is unneeded

**Comment by xCalifier** [comment]
I was able to get lh3.googleusercontent.com link from http://getvideodrive.com/ 

But, is there any easy approach to get that link programmatically
