### ISSUE TITLE
Script does not give back the streaming link

### ISSUE THREAD

**Issue by comtrends123** [ArdiArtani/Google-Drive-Player-Script#32]
Did I do something wrong? Because I cannot see get the iframe box after clicking the get button. Is there the other way to get the streaming link? Currently I am using MAMP to run on locally. Is this work only on the root folder of a website only? I am by no means a web developer so forgive me if I am missing something blindly obvious.

![](http://i.imgur.com/8GjJ28K.png)

**Comment by chopraaa** [comment]
It won't work locally.

**Comment by RiseCoder** [comment]
Drive + All Qualifications + Open Source + Magnificent Player System Only 100$

Demo: http://driver.rangeplayer.com/

User Name: admin
Password: demo

**Comment by comtrends123** [comment]
@chopraaa It still does not work on my host either. I still cannot see the get embed iframe box. So basically it is like my local.

![](http://i.imgur.com/jS4w1Qw.png)

**Comment by chopraaa** [comment]
It shows file cannot be played when a daily limit is reached.

**Comment by comtrends123** [comment]
@chopraaa No, I mean the get embed iframe in my page is not shown like in the demo page.

**Comment by chopraaa** [comment]
It isn't supposed to be the same, it's just a demo. You can modify it to display the embed code.

**Comment by comtrends123** [comment]
Sorry for asking this but do you know how to call this source url from the script? I have tried `<?php echo $ ?>` and it seem like it does not correct.
![](http://i.imgur.com/2dRL8pG.png)

**Comment by hak-jame** [comment]
Hi, How can I get the iframe embed url shown at the bottom of the video just like the demo. I did try too but it didn't work for me. Thanks in advance.

**Comment by dweapons** [comment]
Sir can you make same script for pcloud.com  ?

**Comment by threathgfx** [comment]
@hak-jame 
`<?php
error_reporting(0);
include "curl_gd.php";
if(isset($_GET)){
	$id = base64_decode($_GET['id']);
	$linkdown = Drive("https://drive.google.com/file/d/$id/view");
	$file = '[{"type": "video/mp4", "label": "HD", "file": "'.$linkdown.'"}]';
} else {
	die("Please provide ID.");
}
?>
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
	<title>Get link Google Drive</title>
</head>
<body>

  
  <link rel="stylesheet" href="https://cdn.plyr.io/2.0.13/demo.css">
	<style>
		.container {
		  max-width: 800px;
		  margin: 0 auto;
		}
	</style>

	<div class="container">

		<div id="myElement">Paste the url and click the get button.</div>

	</div>

	<script src="https://content.jwplatform.com/libraries/DbXZPMBQ.js"></script>
	<script type="text/javascript">
		jwplayer("myElement").setup({
			playlist: [{
				"sources":<?php echo $file?>
			}],
			allowfullscreen: true,
			width: '100%',
			aspectratio: '16:9',
		});
	</script>

</body>
</html>`

**Comment by hak-jame** [comment]
@threathgfx

Thank you so much for your reply. I did really appreciate your helping.

After applying your code into the index file by replacing all orginal source. It didn't work as it shown in demo. I did try to correct some your code since it didn't work, but it still don't work at all.
I host all those files in the different directory inside root directory. **here it is** http://eroticmovie.vsharetoday.info/drivescript/

**Here it is my custom index code**
<?php
error_reporting(0);
include "curl_gd.php";
if($_POST['submit'] != ""){
	//$url = $_POST['url'];
$id = base64_decode($_POST['url']);
	//$linkdown = Drive($url);
$linkdown = Drive("https://drive.google.com/file/d/$id/view");
	///$file = '[{"type": "video/mp4", "label": "HD", "file": "'.$linkdown.'"}]';
$file = '[{"type": "video/mp4", "label": "HD", "file": "'.$linkdown.'"}]';
}
?>
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
	<title>Get link Google Drive</title>
</head>
<body>

  
  <link rel="stylesheet" href="https://cdn.plyr.io/2.0.13/demo.css">
	<style>
		.container {
		  max-width: 800px;
		  margin: 0 auto;
		}
	</style>

	<div class="container">
		<br />
		<form action="" method="POST">
			<input type="text" size="80" name="url" value="0ByaRd0R0Qyatcmw2dVhQS0NDU0U"/>
			<input type="submit" value="PLAY" name="submit" />
		</form>
		<br/>

		<div id="myElement">Paste the url and click the get button.</div>

	</div>

	<script src="https://content.jwplatform.com/libraries/DbXZPMBQ.js"></script>
	<script type="text/javascript">
		jwplayer("myElement").setup({
			playlist: [{
				"sources":<?php echo $file?>
			}],
			allowfullscreen: true,
			width: '100%',
			aspectratio: '16:9',
		});
	</script>
<?php
//echo $id;
?>

</body>
</html>

**=> Just make sure that you could see what I really need, so I attached an image below:**
![iframe-display](https://user-images.githubusercontent.com/24820695/29589594-d26373f0-8763-11e7-9ea7-d0a7007be26a.jpg)

Again, thank your for help.

**Comment by Zebraslive** [comment]
@hak-jame 
That url= is the cache file, so just create a file called embed.php including the curl_gd and grab that cache hash from url param then check the cache as drive id with the Drive function. something like that. I can post a working example for u later today when I have more time.

**Comment by hak-jame** [comment]
@Zebraslive 

Thank you so much. I will try it again. However please post that working example because I am really new for coding. I do appreciate for your help.

Have a good evening.
Best.

**Comment by Zebraslive** [comment]
```<?php
error_reporting(0);
include "curl_gd.php";
if(isset($_GET)){
	$id = base64_decode($_GET['id']);
	$linkdown = Drive("https://drive.google.com/file/d/$id/view");
	$file = '[{"type": "video/mp4", "label": "HD", "file": "'.$linkdown.'"}]';
} else {
	die("Please provide ID.");
}
?>```

**Comment by Zebraslive** [comment]
@hak-jame 
The simple way without modifying the main functions. 
Create a file called embed.php and add this
```php
<?php
error_reporting(0);
include "curl_gd.php";

if($_GET['url'] != ""){
	$url = $_GET['url'];
	$linkdown = Drive($url);
	$file = '[{"type": "video/mp4", "label": "HD", "file": "'.$linkdown.'"}]';
}
?>
<div id="myElement">
		    
		</div>
		<script src="https://content.jwplatform.com/libraries/DbXZPMBQ.js"></script>
	<script type="text/javascript">
		jwplayer("myElement").setup({
			playlist: [{
				"sources":<?php echo $file?>
			}],
                skin: {
       name: "stormtrooper",
       active: "mediumpurple",
       inactive: "#bcbcbc",
       background: "rgba(65, 65, 65, 0.82)"
    },
			allowfullscreen: true,
			width: '100%',
			aspectratio: '16:9',
		});
	</script>
```
To output the iframe in textbox just change code at the top of the index.php file to this
**Be sure to add your site url to the $iframex variable**
```php
<?php
error_reporting(0);
include "curl_gd.php";

if($_POST['submit'] != ""){
	$url = $_POST['url'];
	$linkdown = Drive($url);
	$file = '[{"type": "video/mp4", "label": "HD", "file": "'.$linkdown.'"}]';
    $iframex = '<textarea class="form-control" style="margin:10px;width: 97%;height: 80px;"><iframe src="http://yoursite.com/embed.php?url='.$url.'" width="640" height="360" frameborder="0" scrolling="no" allowfullscreen</iframe></textarea>'; 
} else {
    $iframex = "";
}
?>
```
Then just echo iframex below the video, for example I put it above the jwplayer script
```php
<?php
    echo $iframex; 
    ?>
	<script src="https://content.jwplatform.com/libraries/DbXZPMBQ.js"></script>
```

**Comment by hak-jame** [comment]
@Zebraslive 
Thank you so much. Yes, It is working perfectly. However, how can you encrypted the google url that should be display in the ifram. I would like to have just like the Demo (http://google.filedeo.com/).

**Here what is look like after I replace your code.** 
http://eroticmovie.vsharetoday.info/drivescript/

Again, thanks for your help.

**Comment by hak-jame** [comment]
@Zebraslive 

After trying to encode, finally I did. it might not really secure but should be good to use.

Again, thanks for your help and time.
Best.

**Comment by dweapons** [comment]
@hak-jame  

Can you share how you encrypt url ? also still i am not able to get iframe code. i got this type of iframe url which is not working.

embed.php?url=https://drive.google.com/file/d/0ByaRd0R0Qyatcmw2dVhQS0NDU0U/view

**Comment by hak-jame** [comment]
@dweapons 
First, you need to work with unencrypted url first. if can see the above comment of @Zebraslive . he showed me how to do that. You may just follow his steps. Once you got that work. then I will show how to encrypt. Note: make sure you have a basic file from here : https://github.com/ArdiArtani/Google-Drive-Player-Script

**Comment by dweapons** [comment]
@hak-jame i installed script and edit script with @zebraslive step. then i am getting iframe code with above url which i commented. and how can i encrypt url now like demo script.

**Comment by ArdiArtani** [comment]
Updated the script download the new verison.

**Comment by dweapons** [comment]
@ArdiArtani  Sir when i try to edit index.php to get direct play video by url like mysite.com/drive/?id=0ByaRd0R0Qyatcmw2dVhQS0NDU0U but same null embedded code generated every time.

below is my edit 

<?php
error_reporting(0);
include "curl_gd.php";

if($_POST['submit'] != ""){
	$url = $_POST['url'];
	$linkdown = Drive($url);
	$file = '[{"type": "video/mp4", "label": "HD", "file": "'.$linkdown.'"}]';
}

if(isset($_GET)){
	$id = $_GET['id'];
	$linkdown = Drive("https://drive.google.com/file/d/$id/view");
	$file = '[{"type": "video/mp4", "label": "HD", "file": "'.$linkdown.'"}]';
} else {
	die("Please provide ID.");
}
?>

generated null code 

<iframe src="http://mysite.com/drive/embed.php?url=cm5LTUxBUUlYM0FDNlJlMllmNm1Ldz09" width="640" height="360" frameborder="0" scrolling="no" allowfullscreen></iframe>

any solution ?

**Comment by ArdiArtani** [comment]
@dweapons Replace index.php with this.
```
<?php
error_reporting(0);
include "curl_gd.php";

if (isset($_GET)) {
   $id = $_GET['id'];
   $iframeid = my_simple_crypt($id);
   $linkdown = Drive("https://drive.google.com/file/d/$id/view");
   $file = '[{"type": "video/mp4", "label": "HD", "file": "'.$linkdown.'"}]';
} else {
   die("Please provide ID.");
}

if($_POST['submit'] != ""){
   $url = $_POST['url'];
   $gid = get_drive_id($url);
   $iframeid = my_simple_crypt($gid);
   $linkdown = Drive($url);
   $file = '[{"type": "video/mp4", "label": "HD", "file": "'.$linkdown.'"}]';
}
?>

<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<title>Embed google drive generator</title>
</head>
<body>

	<!-- Docs styles -->
	<link rel="stylesheet" href="https://cdn.plyr.io/2.0.13/demo.css">
	<style>
		.container {
		  max-width: 800px;
		  margin: 0 auto;
		}
	</style>

	<div class="container">
		<br />
		<form action="" method="POST">
			<input type="text" size="80" name="url" value="https://drive.google.com/file/d/0ByaRd0R0Qyatcmw2dVhQS0NDU0U/view"/>
			<input type="submit" value="GET" name="submit" />
		</form>
		<br/>

		<div id="myElement">Paste the url and click the get button.</div>

		<div><?php if($iframeid){echo '<textarea style="margin:10px;width: 97%;height: 80px;">&lt;iframe src="/embed.php?url='.$iframeid.'" width="640" height="360" frameborder="0" scrolling="no" allowfullscreen&gt;&lt;/iframe&gt;</textarea>';}?></div>
	</div>

	<script src="https://content.jwplatform.com/libraries/DbXZPMBQ.js"></script>
	<script type="text/javascript">
		jwplayer("myElement").setup({
			playlist: [{
				"sources":<?php echo $file?>
			}],
			allowfullscreen: true,
			width: '100%',
			aspectratio: '16:9',
		});
	</script>

</body>
</html>
```

**Comment by adeadw** [comment]
Hi im new,

im just wondering, is there any way to change the resolution? (360,480,720)
when using the google iframe url preview : https://drive.google.com/file/d/0B9LPSEw89uQNeHdnbVhfVFAxWlE/preview

it will automatically detect the resolution from highest to lowest. is it possible to make that appear? or at least choose the lowest resolution by default.

**Comment by Zebraslive** [comment]
@adeadw its grabbing the video from the download link so i dont think its possible like that other script that can give all resolutions. This one is using a more simplified way of getting the videos direct link.

**Comment by threathgfx** [comment]
@Zebraslive is this still prone to limitation quota?

**Comment by Zebraslive** [comment]
@threathgfx Not sure, as far as I can tell it looks like it should be safe from limits.
@ArdiArtani Can you confirm that it's not possible to retrieve all resolution links? Seems like it's possible.

**Comment by dweapons** [comment]
i tried to add this function player script but its not working. how can i add below function?

autostart: false,
image:"<?php echo $shot;?>",

and below is php part

`<?php
error_reporting(0);
include "curl_gd.php";

if (isset($_GET)) {
   $id = $_GET['id'];
   $iframeid = my_simple_crypt($id);
   $linkdown = Drive("https://drive.google.com/file/d/$id/view");
   $file = '[{"type": "video/mp4", "label": "HD", "file": "'.$linkdown.'"}]';
   $shot = "https://drive.google.com/vt?".$_SERVER["QUERY_STRING"];
} else {
   die("Please provide ID.");
}

if($_POST['submit'] != ""){
   $url = $_POST['url'];
   $gid = get_drive_id($url);
   $iframeid = my_simple_crypt($gid);
   $linkdown = Drive($url);
   $file = '[{"type": "video/mp4", "label": "HD", "file": "'.$linkdown.'"}]';
}
?>`
