### ISSUE TITLE
Direct play by id instead manual click on play button

### ISSUE THREAD

**Issue by dweapons** [ArdiArtani/Google-Drive-Player-Script#33]
How can i direct play by google drive id instead manually paste link and click on play.

i want to directly play video when user open below link.

http://site.com/index.php?id=0ByaRd0R0Qyatcmw2dVhQS0NDU0U

**Comment by monster1777** [comment]
Replace index.php with this.
`<?php
error_reporting(0);
include "curl_gd.php";
if(isset($_GET)){
	$id = $_GET['id'];
	$linkdown = Drive("https://drive.google.com/file/d/$id/view");
	$file = '[{"type": "video/mp4", "label": "HD", "file": "'.$linkdown.'"}]';
} else {
	die("Please provide ID.");
}
?>
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
	<title>Get link Google Drive</title>
</head>
<body>

  
  <link rel="stylesheet" href="https://cdn.plyr.io/2.0.13/demo.css">
	<style>
		.container {
		  max-width: 800px;
		  margin: 0 auto;
		}
	</style>

	<div class="container">

		<div id="myElement">Paste the url and click the get button.</div>

	</div>

	<script src="https://content.jwplatform.com/libraries/DbXZPMBQ.js"></script>
	<script type="text/javascript">
		jwplayer("myElement").setup({
			playlist: [{
				"sources":<?php echo $file?>
			}],
			allowfullscreen: true,
			width: '100%',
			aspectratio: '16:9',
		});
	</script>

</body>
</html>`

**Comment by dweapons** [comment]
thanks . its working now.
