### ISSUE TITLE
Not all link from google drive is working

### ISSUE THREAD

**Issue by aalfiann** [ArdiArtani/Google-Drive-Player-Script#35]
I've been use this script for many days. this script is working until i found this link from google drive >> [https://drive.google.com/file/d/0B9EbJgg4jRodMk5LU0Z6azJ0YkU/view](https://drive.google.com/file/d/0B9EbJgg4jRodMk5LU0Z6azJ0YkU/view).

Actualy the above link is fine but i cant stream that link into my jw player, it shows blank. How to fix this? thanks.

**Comment by dbr4389** [comment]
This script streams from the download link and since you can't download the file due to quota exceeded. You also can't play the video.

**Comment by Zebraslive** [comment]
@dbr4389 Do you know what the quota is? or how it can be avoided? I'm running multiple drive accounts if that helps.

**Comment by Qwatuz** [comment]
Quota is maybe 2TB/day download.

**Comment by aalfiann** [comment]
Quota? My quota, server quota, or google quota? still i dont understand it.

I try to grab using demo >> [http://google.filedeo.com/embed.php?url=YTN5R0lmL1FVeG95MEVaOCtrUTNrZjErRDFVRGMwMERGaTAxVVFpNCtDYz0=](http://google.filedeo.com/embed.php?url=YTN5R0lmL1FVeG95MEVaOCtrUTNrZjErRDFVRGMwMERGaTAxVVFpNCtDYz0=), also shows blank or no playable sources found

**Comment by aalfiann** [comment]
@Zebraslive Yes, multiple account maybe it helps.

In my opnion this is not about the quota, because if using link like https://r5---sn-npoe7n7y.c.drive.google.com/videoplayback?id=xxx, the movie is playing fine.

**Comment by Zebraslive** [comment]
@aalfiann Your video works fine for my copy of the script. The reason it doesn't work on the demo one is because there is a problem with the last update when he added the encrypted url to the iframe and I don't think he noticed yet that it's broken. Just use the old version without encrypting the url. I think it was this commit https://github.com/ArdiArtani/Google-Drive-Player-Script/tree/c489ff826c55ab84689c84d1ec982fe3d4060d56

That being said, there still may be issues with download limitations to a specific file or it could be linked to all files on one account, I guess no one knows for sure what it's based on.

**Comment by MasterEGA** [comment]
mkv video format is not workking! this is just for mp4 :-(

**Comment by threathgfx** [comment]
@MasterEGA convert it using handbrake or vlc

**Comment by aalfiann** [comment]
Thanks.. @Zebraslive i've been take a look all history changes from commit and tried it one by one but still not fix my issue. Actually i've tried by using phpinit and i found function Drive("https://drive.google.com/file/d/0B9EbJgg4jRodMk5LU0Z6azJ0YkU/view") its return empty. so it's not related with encrypting url.

**Comment by aalfiann** [comment]
@MasterEGA when you upload mkv file into google drive, it will be auto converted to mp4. i've so many video with format mkv in google drive and its running fine in jw player with type video/mp4.

**Comment by dbr4389** [comment]
do you have a paid plan?

**Comment by Zebraslive** [comment]
@aalfiann Yea that's weird, it worked for my site the other day, now it's not working with ur link.  Wonder what could cause that to happen though....maybe it could happen at anytime with any url. I think i might make a fallback for when it fails to load, just output the preview link in an iframe https://drive.google.com/file/d/0B9EbJgg4jRodMk5LU0Z6azJ0YkU/preview

**Comment by RiseCoder** [comment]
Drive + All Qualifications + Open Source + Magnificent Player System Only 100$

Demo: http://driver.rangeplayer.com/

User Name: admin
Password: demo

Skype: info@rangeplayer.com

**Comment by dweapons** [comment]
Can anyone tell which script is used by below sites. they are using google drive to store and download and stream. i have found many sites are using same script. 

topddl.net
acefile.co

when we open download link then first it copy that file to our google drive then it gives direct download link or stream. so we can hide actual google drive file.

**Comment by bindepzai** [comment]
Demo: http://xemlaco.net/api/gdrive/play.php?url=https://drive.google.com/file/d/0B9EbJgg4jRodMk5LU0Z6azJ0YkU
Inbox me

**Comment by milankragujevic** [comment]
@bindepzai You're proxying the stream, that's old news, and useless.

**Comment by aalfiann** [comment]
@dweapons you can hide the actual direct link from google drive if using proxy.

@bindepzai i think using proxy is not the solution, because if the proxy is dead then the video link will die too.

**Comment by RiseCoder** [comment]
Google Drive and Other Platform Player Api Service

Fast, secure, fixed price guarantee.

Supports: Google Drive, Google Photos, Youtube, Vimeo, Vid.me, Dropbox

Demo: http://www.playersapi.com

Our API currently costs roughly $1 per 1,000 requests. Requests for the same link within an day are not charged.

Skype : api@playersapi.com

**Comment by aalfiann** [comment]
today, i got my video working fine. actualy i did not change any code. so i guess the problem is from google not in this script.

so this issues should be closed. thanks, this is an awesome script. this is really help me so much.
