### ISSUE TITLE
not a streamable links

### ISSUE THREAD

**Issue by jhaylee2016** [ArdiArtani/Google-Drive-Player-Script#37]
i mean this script does not provide redirector link...

**Comment by RiseCoder** [comment]
Google Drive and Other Platform Player Api Service

Fast, secure, fixed price guarantee.

Supports: Google Drive, Google Photos, Youtube, Vimeo, Vid.me, Dropbox

Demo: http://www.playersapi.com

Our API currently costs roughly $1 per 1,000 requests. Requests for the same link within an day are not charged.

Skype : api@playersapi.com

**Comment by jhaylee2016** [comment]
@RiseCoder im sorry im not interested..by the way thanks for the offer...i already have those script except google drive...

**Comment by threathgfx** [comment]
@jhaylee2016 this script is still inprogress.

**Comment by Zebraslive** [comment]
Anyone know what he google.mp3 is for? do i need it?

**Comment by milankragujevic** [comment]
@Zebraslive It's cookie storage, you do need it.

**Comment by ArdiArtani** [comment]
Duplicate of #7
