### ISSUE TITLE
Link not working next day!

### ISSUE THREAD

**Issue by nik0s100** [ArdiArtani/Google-Drive-Player-Script#38]
I'm trying to watch a link I deleted cache and google.mp3 which I don't know why is there like a cookie.
But still not working. When I run this on localhost same link it works fine.

Link which doesn't work: https://cinemate.tv/Watch/F8b9J4vn2IvQKpFrJxe8pBc7yDnNe9cT

Drive link: https://drive.google.com/file/d/0B__9D-CNHa-leExmNVM0Wks0Y1U/view

**Comment by Myllz** [comment]
You've reached google drive download limit.

**Comment by nik0s100** [comment]
I don't think so. It works fine on localhost

**Comment by wteran** [comment]
have u tried using docs. instead of drive. that way uses it from a different server dedicated for groups and blogs.

**Comment by nik0s100** [comment]
No but I can't directly upload videos in there

**Comment by Zebraslive** [comment]
Can anyone tell me what http code is returned when limit is reached? or is there anything on the page that it says like a specific message I can parse for detecting failure to load? I need to make a fallback script.

**Comment by dungvaph03374** [comment]
if you're using jwplayer, use event error to gerenate new link

**Comment by aalfiann** [comment]
Remember that google drive will allow to run playback for 1000 user watching. If more, you will get error failure.

**Comment by dungvaph03374** [comment]
@Zebraslive
`{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "downloadQuotaExceeded",
    "message": "The download quota for this file has been exceeded."
   }
  ],
  "code": 403,
  "message": "The download quota for this file has been exceeded."
 }
}`
@aalfiann just for sure, 1000 ip can request many time or just 1000 request per video, i'm making an anime site :)

**Comment by aalfiann** [comment]
@dungvaph03374 Google Drive only limit request 1000 user watching at same time per video. Not from IP address.

**Comment by mangemve1511** [comment]
@ArdiArtani Hi, i use your script but some link have not sound when i play by Safari browser or mobile, although it's .mp4 file. Can you help me? Thank you!

**Comment by ArdiArtani** [comment]
@mangemve1511 Can you share the link let me take a look

**Comment by mangemve1511** [comment]
@ArdiArtani This link: [https://drive.google.com/file/d/0B0xiPwPds6wHMmZ6U2ZxZmNKQzg/view](https://drive.google.com/file/d/0B0xiPwPds6wHMmZ6U2ZxZmNKQzg/view)

**Comment by ArdiArtani** [comment]
link is working

**Comment by mangemve1511** [comment]
@ArdiArtani Do you play in Safari browser or mobile?

**Comment by ArdiArtani** [comment]
@mangemve1511 Google Chrome, Safari, Opera and Safari (iPhone 7). Clean your browser cache and the cached files in the cache folder.

**Comment by viethqph00671** [comment]
better use googleapis drive v3, easy & simple, no worry about link die
