### ISSUE TITLE
I do not want the video to play automatically.

### ISSUE THREAD

**Issue by aplusing** [ArdiArtani/Google-Drive-Player-Script#39]
How i can fix?

**Comment by Leonsss** [comment]
at this code
`<script src="https://content.jwplatform.com/libraries/DbXZPMBQ.js"></script>
	<script type="text/javascript">
		jwplayer("myElement").setup({
			playlist: [{
				"sources":<?php echo $file?>
			}],
			allowfullscreen: true,
			width: '100%',
			aspectratio: '16:9',
		});
	</script>`

add this :  autostart: 'false'. The code will look like this:
`<script src="https://content.jwplatform.com/libraries/DbXZPMBQ.js"></script>
	<script type="text/javascript">
		jwplayer("myElement").setup({
			playlist: [{
				"sources":<?php echo $file?>
			}],
			allowfullscreen: true,
			width: '100%',
			aspectratio: '16:9',
                        autostart: 'false'
		});
	</script>`
