### ISSUE TITLE
Direct link support pleas

### ISSUE THREAD

**Issue by ugurkorkmazyurek** [ArdiArtani/Google-Drive-Player-Script#40]
I want to play the video directly. Can you help ?

**Comment by threathgfx** [comment]
You mean like this?
```
<?php
header("Location: $files");
die();
?>
```

**Comment by ugurkorkmazyurek** [comment]
How is direct link support provided?

**Comment by Zebraslive** [comment]
Sorry, can you be more specific? @ugurkorkmazyurek 
It already gives direct link from drive function. You don't need to embed with iframe or use encrypted urls.
 This is one example how I use the script.
```php
<?php
include "curl_gd.php";

if($_GET['url'] != ""){
	$subfject = $_GET['url'];
    if (strpos($subfject, 'drive.google.com/file/d/') !== false) {
    $pattern='/(?<=file\/d\/)(.*)(?=\/)/';
    $succefss = preg_match($pattern, $subfject, $maftch);
    $dbken = $maftch[0];
} else if (strpos($subfject, 'drive/v3/files') !== false) {
    $pattern = '/(?<=drive\/v3\/files\/)(.*)(?=\?alt)/';
     
     $succefss = preg_match($pattern, $subfject, $maftch);
    $dbken = $maftch[0];
   
} else {
$dbken = $_GET['url']; //instead of full link, grab using just id.
   
}
	
	$title = fetch_value(file_get_contents_curl('https://drive.google.com/get_video_info?docid='.$dbken), "title=", "&");
	$url = 'https://drive.google.com/file/d/'.$dbken.'/view';
	$linkdown = Drive($url);
	  $vid['result'][0] = array();
  $vid['result'][0]['info']['title'] = $title;
          $vid['result'][0]['link'] = $linkdown;
    $vidarray = json_encode($vid);
echo $vidarray;
}

//accessing the url and info in array.
$VideoTitle = urldecode($vid['result'][0]['info']['title']);
$urlvi = urldecode($vid['result'][0]['link']);
?>
```

**Comment by ugurkorkmazyurek** [comment]
Example (Google Drive Direct Link): http://www.ugurkorkmazyurek.com/d/s6s39zwghu6tpnxu.php?id=0B5zYKCowk_YpVi1MVVA1MkRkdHM

https://drive.google.com/file/d/0B30cNtbbmE30Yl9zRVktaE9ROUk/view

**Comment by Zebraslive** [comment]
@ugurkorkmazyurek this downloads directly with the filename same as the videos.
```php
<?php
include "curl_gd.php";

if($_GET['url'] != ""){
	$subfject = $_GET['url'];
    if (strpos($subfject, 'drive.google.com/file/d/') !== false) {
    $pattern='/(?<=file\/d\/)(.*)(?=\/)/';
    $succefss = preg_match($pattern, $subfject, $maftch);
    $dbken = $maftch[0];
} else if (strpos($subfject, 'drive/v3/files') !== false) {
    $pattern = '/(?<=drive\/v3\/files\/)(.*)(?=\?alt)/';
     
     $succefss = preg_match($pattern, $subfject, $maftch);
    $dbken = $maftch[0];
   
} else {
$dbken = $_GET['url'];
   
}
	
	$title = fetch_value(file_get_contents_curl('https://drive.google.com/get_video_info?docid='.$dbken), "title=", "&");
	$url = 'https://drive.google.com/file/d/'.$dbken.'/view';
	$linkdown = Drive($url);
$filename = str_replace(' ', '-', strtolower(urldecode($title)));
  header('Content-Disposition: attachment; filename="'.$filename.'.mp4"');
header('Location: '.$linkdown.'');
    
}


?>
```

**Comment by mirmarshall01** [comment]
@Zebraslive : can you help create the download code with different resolution (multiple size download option)

The case is like this : 
-  i have upload video with 1080p resolution
- i want to download the video file in 1080p/720p/480p/360p resolution

please help :D

**Comment by milankragujevic** [comment]
@mirmarshall01 Yeah no, that is not possible.

**Comment by mirmarshall01** [comment]
take a look on this website http://en.indoxxi.net/

that what i'm talking about :D

**Comment by Zebraslive** [comment]
@mirmarshall01 The same dude already made this https://github.com/ArdiArtani/Photo-Google-Player-Script and it grabs all resolutions. Works perfectly. Hope it lasts.

**Comment by mirmarshall01** [comment]
@Zebraslive but my file is in google drive, not in google photo

**Comment by viethqph00671** [comment]
you can convert video resolution from hd to sd then upload to drive, in case you have unlimited storage and time, never have to worry about google change algorithm

**Comment by haxunivil** [comment]
Simple and reliable script for generating HTML5 video streaming links from Google Drive files.
it's not a proxy script, provide links direct to Google’s Video CDN
Easy Installation, You just need PHP hosting and Google Cloud PHP App account thats all, now you are ready to fly.
It's work with all public google drive videos on free and gsuite accounts.

Buy Google Drive Stream Links Script and TEST IT:
https://google.driveplayer.stream/

**Comment by zeydhan** [comment]
Hello, if you're looking for gdrive player that return lh3.googleusercontents link, please go to : www.gdriveplayer.us

plugin and API documentation is available there

Basically, here's how to use : http://gdriveplayer.us/embed2.php?link={insert link drive here}

Good luck
