### ISSUE TITLE
How i can set cover image?

### ISSUE THREAD

**Issue by aplusing** [ArdiArtani/Google-Drive-Player-Script#41]
i'm insert image below code but it's not show my image
How i can set cover image?
```
<script type="text/javascript">
		jwplayer("myElement").setup({
			playlist: [{
				"sources":<?php echo $file?>
			}],
			allowfullscreen: true,
			image: "https://kawaiian.tv/program/nmb48-theater/img/cap_01.jpg",
			autostart: false,
			width: '100%',
			aspectratio: '16:9',
		});
	</script>
```

**Comment by Zebraslive** [comment]
add this to the curl_gd.php file
```php
function PosterImg($url) {
$html = new simple_html_dom();
$html->load_file($url);
return $html->find('meta[property=og:image]',0)->attr['content'];
}
```

Then you can call it like this 
```php

PosterImg('https://drive.google.com/file/d/XXXXXXXXXXX/preview');
```

**Comment by aplusing** [comment]
@Zebraslive
i added your code to the curl_gd.php file.
i tried call code below to curl_gd.php or index.php but show cover image.
`$posterimg = PosterImg('https://drive.google.com/file/d/XXXXXXXXXXX/preview');`
you can teach me.?  ;_;

**Comment by timekills** [comment]
`<script` type='text/javascript'>
    jwplayer("myElement").setup({
        "sources":[{
               <?php echo $file?>
			}],
	allowfullscreen: true,
        autostart: false,
// URL to the image that should be shown before the video is started
        image: "https://kawaiian.tv/program/nmb48-theater/img/cap_01.jpg",
        title: "Whatever",
        width: "100%",
        aspectratio: "16:9"
    });
</script>``

**Comment by Zebraslive** [comment]
@aplusing 
Just echo out the img variable into the script. 
```php
<?php
if($_GET['url'] != ""){
	$subfject = $_GET['url'];
    if (strpos($subfject, 'drive.google.com/file/d/') !== false) {
    $pattern='/(?<=file\/d\/)(.*)(?=\/)/';
    $succefss = preg_match($pattern, $subfject, $maftch);
    $dbken = $maftch[0];
} else if (strpos($subfject, 'drive/v3/files') !== false) {
    $pattern = '/(?<=drive\/v3\/files\/)(.*)(?=\?alt)/';
     $succefss = preg_match($pattern, $subfject, $maftch);
    $dbken = $maftch[0];
} else {
$dbken = $_GET['url']; //use file id only if url isn't detected.
}
$backup = 'https://drive.google.com/file/d/'.$dbken.'/preview';
$posterimg = PosterImg($backup);
?>
<script type="text/javascript">
		jwplayer("myElement").setup({
			playlist: [{
				"sources":<?php echo $file?>
			}],
			allowfullscreen: true,
			image: "<?php echo $posterimg; ?>",
			autostart: false,
			width: '100%',
			aspectratio: '16:9',
		});
	</script>
```

**Comment by Bluecozza** [comment]
This one should be worked:
<?php
if($_GET['url'] != ""){
	$subfject = $_GET['url'];
    if (strpos($subfject, 'drive.google.com/file/d/') !== false) {
    $pattern='/(?<=file\/d\/)(.*)(?=\/)/';
    $succefss = preg_match($pattern, $subfject, $maftch);
    $dbken = $maftch[0];
} else if (strpos($subfject, 'drive/v3/files') !== false) {
    $pattern = '/(?<=drive\/v3\/files\/)(.*)(?=\?alt)/';
     $succefss = preg_match($pattern, $subfject, $maftch);
    $dbken = $maftch[0];
} else {
$dbken = $_GET['url']; //use file id only if url isn't detected.
}
$backup = 'https://drive.google.com/file/d/'.$dbken.'/preview';
$posterimg = PosterImg($backup);
?>
<script type="text/javascript">
		jwplayer("myElement").setup({
			playlist: [{
				image: "<?php echo $posterimg; ?>",
				"sources":<?php echo $file?>
			}],
			allowfullscreen: true,
			autostart: false,
			width: '100%',
			aspectratio: '16:9',
		});
	</script>

put image inside playlist brace
