### ISSUE TITLE
How i can set subtitle for the video ?

### ISSUE THREAD

**Issue by mirmarshall01** [ArdiArtani/Google-Drive-Player-Script#42]

**Comment by mangemve1511** [comment]
Hi @ArdiArtani, can you write func add link subtitle? Thanks so much!

**Comment by ArdiArtani** [comment]
@mirmarshall01 @mangemve1511 [https://support.jwplayer.com/customer/portal/articles/1407438](https://support.jwplayer.com/customer/portal/articles/1407438)
