### ISSUE TITLE
Hi . Some videos have no audio and video can fix pls ?

### ISSUE THREAD

**Issue by matamune1994** [ArdiArtani/Google-Drive-Player-Script#43]
EX : No have audio https://drive.google.com/file/d/0BxvQyG88Ppcdbkd0alZENVNJNmc/view?usp=sharing

No have video : https://drive.google.com/file/d/0ByaRd0R0Qyatcmw2dVhQS0NDU0U/view
can fix pls ?

**Comment by Zebraslive** [comment]
that's pretty weird.....Have you tried re-uploading it?
Not sure why it would do that. The audio one won't work at all. But this one works normaly for me https://jauntiest-ages.000webhostapp.com/drive/embed.php?id=https://drive.google.com/file/d/0ByaRd0R0Qyatcmw2dVhQS0NDU0U/view

**Comment by haxunivil** [comment]
Simple and reliable script for generating HTML5 video streaming links from Google Drive files.
it's not a proxy script, provide links direct to Google’s Video CDN
Easy Installation, You just need PHP hosting and Google Cloud PHP App account thats all, now you are ready to fly.
It's work with all public google drive videos on free and gsuite accounts.

Buy Google Drive Stream Links Script and TEST IT:
https://google.driveplayer.stream/

**Comment by zeydhan** [comment]
Hello, if you're looking for gdrive player that return lh3.googleusercontents link, please go to : www.gdriveplayer.us

plugin and API documentation is available there

Basically, here's how to use : http://gdriveplayer.us/embed2.php?link={insert link drive here}

Good luck
