### ISSUE TITLE
PosterImg not show after embed video

### ISSUE THREAD

**Issue by nsultaan** [ArdiArtani/Google-Drive-Player-Script#45]

**Comment by nsultaan** [comment]
please add image preview code in embed.php

**Comment by Zebraslive** [comment]
It's already been added.

**Comment by ArdiArtani** [comment]
nsultaan@edecac3ad9902dac52de9d59ef97fdf4872da1c1

**Comment by nsultaan** [comment]
Still Not Work

**Comment by mocophat** [comment]
@nsultaan 
Replace embed.php with this

`<?php
error_reporting(0);
include "curl_gd.php";

if($_GET['url'] != ""){
	$gid = $_GET['url'];
	$original_id = my_simple_crypt($gid, 'd');
	$title = fetch_value(file_get_contents_curl('https://drive.google.com/get_video_info?docid='.$original_id), "title=", "&");
	$url = 'https://drive.google.com/file/d/'.$original_id.'/view';
	$linkdown = Drive($url);
	$file = '[{"type": "video/mp4", "label": "HD", "file": "'.$linkdown.'"}]';
	$backup = 'https://drive.google.com/file/d/'.$original_id.'/preview';
	$posterimg = PosterImg($backup);
}
?>
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
	<title><?php echo $title?> - Google Drive</title>
</head>
<body>

	<div id="myElement"></div>

	<script src="https://content.jwplatform.com/libraries/DbXZPMBQ.js"></script>
	<script type="text/javascript">
		jwplayer("myElement").setup({
			playlist: [{
				"image": "<?php echo $posterimg; ?>",
				"sources":<?php echo $file?>
			}],
			allowfullscreen: true,
			autostart: 'false',
			width: '100%',
			aspectratio: '16:9',
		});
	</script>

</body>
</html>`
