### ISSUE TITLE
Is it possible to set the resolution?

### ISSUE THREAD

**Issue by adeadw** [ArdiArtani/Google-Drive-Player-Script#46]
heloo,, firstly i can't thank you more for creating this helpful google drive link generator.

i saw on one of indonesian streaming sites (lk**.co) they've just successfully make new drive generator link with new method which makes visitor to choose which resolution they want to use.. but, the resolution is chosen not inside the player,, i guess and maybe they play with the parameter.

i compare the 360 and 720 version. there is a little different in their links:

================================================================
https://r1---sn-npoeen76.c.drive.google.com/videoplayback?id=0eecff23f46993fd&itag=22&source=webdrive&begin=0&requiressl=yes&mm=30&mn=sn-npoeen76&ms=nxu&mv=m&pl=24&sc=yes&ei=gTXkWZ7vHuucowP7i5VY&driveid=0B6uLaFG6ca3ecWhRWEF0TVFuNHc&mime=video/mp4&lmt=1469594639774154&mt=1508128067&ip=202.62.16.54&ipbits=8&expire=1508135329&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mn,ms,mv,pl,sc,ei,driveid,mime,lmt&signature=1E5AF7A589F4CE9323D87C5FEBE5D99A0FA738FB.7DFEB234FD2CA9D78575A0610E6BCB06C089D8EC&key=ck2&begin=0

https://r1---sn-npoeen76.c.drive.google.com/videoplayback?id=0eecff23f46993fd&itag=18&source=webdrive&begin=0&requiressl=yes&mm=30&mn=sn-npoeen76&ms=nxu&mv=m&pl=24&sc=yes&ei=uDXkWZStCoKuogOH75OYAg&driveid=0B6uLaFG6ca3ecWhRWEF0TVFuNHc&mime=video/mp4&lmt=1469593878005364&mt=1508128067&ip=202.62.16.54&ipbits=8&expire=1508135384&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mn,ms,mv,pl,sc,ei,driveid,mime,lmt&signature=3DF825F7B04FF4271591190BFD198C2A2B722B11.06C695AC8405F302397F0D92A021CC9692EF1428&key=ck2&begin=0
================================================
itag=18
itag=22

even the "driveid=" is exposed, but thay successfully able to generate movie into 3 links with 3 different resolution.

i would be happy if you know how make that happen. and of course will be more helpful to people who plays with gogole drive redirector.

Thank you !

**Comment by dbr4389** [comment]
No, you can't this script streams from the download link.

**Comment by dungvaph03374** [comment]
Sure you can by using get_video_info
Drive link requried cookie DRIVE_STREAM, without it you can't access the link

**Comment by haxunivil** [comment]
Simple and reliable script for generating HTML5 video streaming links from Google Drive files.
it's not a proxy script, provide links direct to Google’s Video CDN
Easy Installation, You just need PHP hosting and Google Cloud PHP App account thats all, now you are ready to fly.
It's work with all public google drive videos on free and gsuite accounts.

Buy Google Drive Stream Links Script and TEST IT:
https://google.driveplayer.stream/

**Comment by aalfiann** [comment]
I have that script, but it need a proxy server to forwarded_for. The disadvantage using proxy is, if your proxy server down, video will error and need a cost to have your own proxy server.

**Comment by dungvaph03374** [comment]
@aalfiann i did once but it slow as hell, basically i just used get_video_info and stream it via PHP

**Comment by aalfiann** [comment]
@dungvaph03374 yeah i know, i also have that proxy that stream using DRIVE_STREAM, the speed is very slow also it create so many log. Have you check the log from that script in your server?

**Comment by ueja32** [comment]
[SELL] Google Drive Direct Links NEW METHOD!!!!
Simple and reliable script for generating HTML5 video streaming links from Google Drive files. 
it's not a proxy script, provide links direct to Google's Video CDN
Easy Installation, You just need PHP hosting and Google Cloud PHP App account thats all, now you are ready to fly. 
It's work with all public google drive videos on free and gsuite accounts.

DEMO AND MORE INFO: https://google.driveplayer.stream/

**Comment by ArdiArtani** [comment]
#7
