### ISSUE TITLE
Free Google Drive Player Script (ADMIN: FRAUD)

### ISSUE THREAD

**Issue by vixape** [ArdiArtani/Google-Drive-Player-Script#53]
ADMIN: FRAUD

**Comment by Zebraslive** [comment]
Dur....It's not safe to use 3rd party api. 
Build your own, host it yourself, no chance of malicious redirects or downtime.
someone report this post....I'm tired of doing it.

**Comment by vixape** [comment]
Zebraslive, you fucking an idiot =)

**Comment by Zebraslive** [comment]
@vixape Right back at cha bitch.
Stop spamming your bullshit and find real work.
