### ISSUE TITLE
Attention - Google.driveplayer.stream Fraud

### ISSUE THREAD

**Issue by EXAlejandro** [ArdiArtani/Google-Drive-Player-Script#54]
Attention - Google.driveplayer.stream and ApiGd.com Fraud

Definitely do not pay.

There is no code to give you. It's a complete fraud.

**Comment by dungvaph03374** [comment]
You bought a script through bitcoin and didn't see that coming, sr for you lost :-1:

**Comment by dungvaph03374** [comment]
Easy as fuck and nobody think about, wth, build a goddamn extension to sync cookie DRIVE_STREAM

![untitled](https://user-images.githubusercontent.com/9255898/32689078-bafb26fe-c70f-11e7-8b64-3a834a535f76.png)

**Comment by wuhad** [comment]
already have full source code. I paid 3 days ago 
If somebody need google drive player i sell it for 80$. 
I can show demo with your links.

Contact me by mail: ismail92@gmail.com

**Comment by japnimedev** [comment]
@dungvaph03374 Inserting cookie thru php doesn't work anymore?

**Comment by gruntduck** [comment]
Oh, my God, they eat my 100$ this site is a froud=> Google.driveplayer.stream 
he is a Fraud pls check the video 
https://www.youtube.com/watch?v=iSNL3mZu7uE
