### ISSUE TITLE
Sell Google Drive LH3 METHOD 360P 480P 720P 1080P

### ISSUE THREAD

**Issue by poeaz** [ArdiArtani/Google-Drive-Player-Script#57]
Simple and reliable script for generating HTML5 video streaming links from Google Drive files. 
it's not a proxy script, provide links direct to Google's Video CDN
Easy Installation, You just need PHP hosting and Google Cloud PHP App account thats all, now you are ready to fly. 
It's work with all public google drive videos on free and gsuite accounts.

MORE INFO AND TEST ON: https://google.driveplayer.stream/

**Comment by ArdiArtani** [comment]
FRAUD!!!!!!!!!!

**Comment by poeaz** [comment]
You dont have money to buy it and you dont know how this method is working its easy to say FRAUD LOL!!

**Comment by ArdiArtani** [comment]
When you have proof of course it's easy to say FRAUD! [https://www.youtube.com/watch?v=iSNL3mZu7uE](https://www.youtube.com/watch?v=iSNL3mZu7uE)

**Comment by bitchardi** [comment]
ArdiArtani get some money and learn how get links on google drive
