### ISSUE TITLE
[PHP] Sell Google Drive LH3 METHOD 360P 480P 720P 1080P

### ISSUE THREAD

**Issue by poeaz** [ArdiArtani/Google-Drive-Player-Script#58]
Simple and reliable script for generating HTML5 video streaming links from Google Drive files.
it's not a proxy script, provide links direct to Google's Video CDN
Easy Installation, You just need PHP hosting and Google Cloud PHP App account thats all, now you are ready to fly.
It's work with all public google drive videos on free and gsuite accounts.

MORE INFO AND TEST ON: https://google.driveplayer.stream/

**Comment by ArdiArtani** [comment]
FRAUDDD!!!
