### ISSUE TITLE
Sometimes we can't get the drive link (the function Drive($link) is return empty)

### ISSUE THREAD

**Issue by aalfiann** [ArdiArtani/Google-Drive-Player-Script#59]
I just applied this script in my production web movie, and sometimes we can't get the drive link.. 

This is only happen for a few users only.

The solution i've made this far is create the auto switch to redirect to google drive link..

But I just want to know why this could happen? so i can fix it.

Thanks

**Comment by Zebraslive** [comment]
what does the error log say for when the video doesn't load? I've never seen this myself. 
so far only errors I've seen 
failed to open stream: php_network_getaddresses: getaddrinfo failed Name or service not known
SSL: Handshake timed out
failed to open stream: HTTP request failed! HTTP/1.0 403 Forbidden
failed to open stream: operation failed

**Comment by dungvaph03374** [comment]
there are plenty of reason so can't figure it out without log, you can listen on error then load the drive api v3 instead https://www.googleapis.com/drive/v3/files/drive_id?alt=media&key=app_key

**Comment by sergeyhartmann** [comment]
@aalfiann 
the same library, but using guzzlehttp https://github.com/sergeyhartmann/streaming-link-generator

**Comment by zeydhan2** [comment]
Hello, the reason is because your google drive link being limited (24 hours limit exceed) so the download link cannot be generated. I have an alternative, you can use player such as www.gdriveplayer.us to bypass this limitation
