### ISSUE TITLE
Google Photo link dies after a short time

### ISSUE THREAD

**Issue by spunszor** [ArdiArtani/Google-Drive-Player-Script#61]
The first time it works great but after a short time the link just shows a symbol.
URL: [https://lh3.googleusercontent.com/nJ10CRlsooFwKUz6bl7BhoOmX8Upnu0IJjTWFmx26SoXZvm6fE7YwcPycwzZfnSTLpeBSXgrZLzJpVNK-QyXIioDhOAl9g3ZF4YT0Euw8t4LsV1eqwjAAVe3D8D88Dr91nMvhPOg4A=m18](https://lh3.googleusercontent.com/nJ10CRlsooFwKUz6bl7BhoOmX8Upnu0IJjTWFmx26SoXZvm6fE7YwcPycwzZfnSTLpeBSXgrZLzJpVNK-QyXIioDhOAl9g3ZF4YT0Euw8t4LsV1eqwjAAVe3D8D88Dr91nMvhPOg4A=m18)

Why is this happening? Any ideas? The video do shows in the Photos Gallery but it cannot be played. If i reupload the same file the link will live probably forever.

**Comment by japnimedev** [comment]
@SpencerSmithHU try to use google plus, here's my beta script `https://github.com/japnimedev/Google-Plus-Stream`

**Comment by SpencerSmithHU** [comment]
@japnimedev. The problem still exists with your Google Plus script.
