### ISSUE TITLE
Subtitle For Video Doesn't Work

### ISSUE THREAD

**Issue by skthanu** [ArdiArtani/Google-Drive-Player-Script#62]
Hello, I don't know why but I added sub for my video on Google Drive, if i watch it from original link, its ok, but with this one, i can not see sub, can you please tell me how can i add sub for this?

**Comment by aalfiann** [comment]
@skthanu Subtitle is client side in JWPlayer. You can just add it directly in the player.

**Comment by Leo01985** [comment]
how add directly in the player? is not posible to upload or add some link?

**Comment by ArdiArtani** [comment]
Please visit the jwplayer site for more information how to add subtitles [https://www.jwplayer.com/](https://www.jwplayer.com/)
