### ISSUE TITLE
New proxy script looking for a code review.

### ISSUE THREAD

**Issue by chopraaa** [ArdiArtani/Google-Drive-Player-Script#68]
I uploaded my streaming script and looking for testers and reviewers. Post an issue in that repository itself.

https://github.com/chopraaa/video-stream-api

Cheers.

**Comment by FloridaStream** [comment]
proxy is bad, because use views quote.... but, whateve...

**Comment by chopraaa** [comment]
@FloridaStream Do you have an alternative?

**Comment by FloridaStream** [comment]
nops
