### ISSUE TITLE
Adding a poster

### ISSUE THREAD

**Issue by pathboot** [ArdiArtani/Google-Drive-Player-Script#72]
hello

please how we can add a poster please !

its possible ?

**Comment by DinoDabs** [comment]
use the PosterImg function.
echo PosterImg("driveurl");

**Comment by pathboot** [comment]
please can you explaint how i can use it ? i see 
                $backup = 'https://drive.google.com/file/d/'.$gid.'/preview';
		$posterimg = PosterImg($backup);

but not working

**Comment by mangemve1511** [comment]
@pathboot Can you show scripts?

**Comment by ArdiArtani** [comment]
Use the function PosterImg($url); to grab the poster image
