### ISSUE TITLE
Proxy Help

### ISSUE THREAD

**Issue by ecchirealm** [ArdiArtani/Google-Drive-Player-Script#75]
Does this script have a proxy code implemented so google won't delete the copyrighted material?

**Comment by milankragujevic** [comment]
First of all, Google uses ContentID to delete and match copyrighted content, and second, no it doesn't have proxy.

**Comment by ecchirealm** [comment]
need proxy, this error shows up
Unable to play this video at this time. The number of allowed playbacks has been exceeded. Please try again later.
So proxy would help overcome it
