### ISSUE TITLE
autoplay

### ISSUE THREAD

**Issue by ecchirealm** [ArdiArtani/Google-Drive-Player-Script#76]
How do you remove autoplay from the player. I looked at the php files and none of them have the "autoplay=true" like most players, any help would be greatly appreciated!

**Comment by Leonsss** [comment]
@ecchirealm try to add `autoplay: false` at the index.php below aspectratio: '16:9'.

**Comment by ecchirealm** [comment]
didn't work do i have to add any ''? can you give an example of the integrationi at work?

**Comment by Leonsss** [comment]
In jwplayer is autostart not autoplay. My bad. Try `autostart: false`

**Comment by VicktorS2** [comment]
I solved!

Go to **index.php** and change _"https://content.jwplatform.com/libraries/DbXZPMBQ.js"_  to _"https://content.jwplatform.com/libraries/vnE1uxPy.js"_

**Comment by ecchirealm** [comment]
i tried that and it didn't work, is that all you did? and are you sure you embeded it?

**Comment by itseasy21** [comment]
set `"autostart": false,` after aspect ratio should work, else use the js link provided by @VicktorS2 , it has autostart disabled by default
