### ISSUE TITLE
why i can not use videojs

### ISSUE THREAD

**Issue by blacky0315** [ArdiArtani/Google-Drive-Player-Script#77]
why i can not use videojs ? not work

**Comment by DinoDabs** [comment]
https://github.com/DinoDabs/Google-Drive-Player-Script/blob/master/embed.php

**Comment by blacky0315** [comment]
not work format not support mp4 files

**Comment by DinoDabs** [comment]
http://yoursite.com/embed.php?url=https://drive.google.com/file/d/0ByaRd0R0Qyatcmw2dVhQS0NDU0U/view
it works...
