### ISSUE TITLE
Scared of Google Drive Video Being Taken Down

### ISSUE THREAD

**Issue by ecchirealm** [ArdiArtani/Google-Drive-Player-Script#80]
Hey, jsut implemented into my site, but i'm scared that if the traffic gets higher, google might notice and take down the google drive vide. Is there any way that we can implement something to prevent this? thanks

**Comment by DinoDabs** [comment]
You have nothing to worry about. I've been using for months with thousands of views daily. I encrypt source url but that doesn't make a difference to google. I only encrypt to prevent others from using my files.

**Comment by ecchirealm** [comment]
could you give me a tutorial on how to encrypt the files?

**Comment by zeydhan2** [comment]
you ca use this link:
http://gdriveplayer.us/embed2.php?link={insert your google drive link here}&subtitle={insert your sub link here}&encrypt=yes

it will return encrypted iframe code, you can place them directly to your website. it can also has bypass limit

**Comment by pathboot** [comment]
@zeydhan2 thanks for the tips but for me i want the script installed in this link, any idea ? because i want my own script if you have any idea im here
thanks

**Comment by mangemve1511** [comment]
Get videos private fb. It’s never die.

**Comment by pathboot** [comment]
@mangemve1511 hi, how we can use it to stream ? more info plz bro

**Comment by mangemve1511** [comment]
@pathboot I sell script. if you need it, contact with me.

**Comment by pathboot** [comment]
@mangemve1511 ok bro add me in skype im online now : pathboot

**Comment by mangemve1511** [comment]
@pathboot Check your skype.

**Comment by Zebraslive** [comment]
Just made this today https://github.com/Zebraslive/MediaFire-Streaming

**Comment by hklcf** [comment]
Free mediafire api

https://github.com/hklcf/MediaFire-Stream-API
