### ISSUE TITLE
Unable to play this video at this time. The number of allowed playbacks has been exceeded. Please try again later.

### ISSUE THREAD

**Issue by ecchirealm** [ArdiArtani/Google-Drive-Player-Script#82]
Unable to play this video at this time. The number of allowed playbacks has been exceeded. Please try again later.
This error shows up after 2k views, any fix?

**Comment by Zebraslive** [comment]
Is that 2k views on one video or the entire account?

**Comment by blacky0315** [comment]
is new google dirve have max 2000 views limit for data

**Comment by ecchirealm** [comment]
any ideas to fix it? any help would be appreciated, as of right now i'm making copy's of the file but it isn't a long run fix. any help would be very appreciated.

**Comment by ecchirealm** [comment]
it's on multiple videos, but as of right now if i try to view the video on google drive, it shows the error message on all the videos on google drive

**Comment by blacky0315** [comment]
give not fix

**Comment by ecchirealm** [comment]
any new fixes?

**Comment by blacky0315** [comment]
no is from google server side , can not fixxed ...

**Comment by zeydhan2** [comment]
Hello. i've done some tweak to bypass this limit. it can be fixed, we still have hope, you can use my free api by calling at this link:
http://gdriveplayer.us/embed2.php?link={enter your limited google drive link here}

please send feedback if you find any error. thanks

**Comment by MediaFireStream** [comment]
You can stream videos from mediafire without limits.
Demo http://giftup.tk/mediafire/ 
You don't have to use 3rd party api, you can host the script yourself.

**Comment by ecchirealm** [comment]
can you add vast (ads) to this script?

**Comment by hklcf** [comment]
https://github.com/hklcf/MediaFire-Stream-API

**Comment by ecchirealm** [comment]
how do u add vast ( ads) to this?

**Comment by MediaFireStream** [comment]
My script includes embed files for easy use but also includes API output.
You can use videojs vast/vpaid plugins with it. I'll add some more features to the script when I have some time. I can also hide full source of the video and add hourly cache.
@ecchirealm use coupon **5off** and get for $5

**Comment by ecchirealm** [comment]
does this include installation service

**Comment by MediaFireStream** [comment]
@ecchirealm I can set it up for you, but it's really not that hard to do. just upload the files and that's it.  
then use like http://yoursite.com/embed.php?u=mediafirelinkhere
or http://yoursite.com/api.php?u=mediafirelinkhere to get json

**Comment by hklcf** [comment]
Free MediaFire embed script and direct link api

https://github.com/hklcf/MediaFire-Stream-API

**Comment by hklcf** [comment]
Free Facebook video embed script and direct link api

https://github.com/hklcf/Facebook-Stream-API

**Comment by DinoDabs** [comment]
@hklcf Facebook deletes a video soon as it's uploaded if it contains any copyrighted sounds. Any way around this? does using private videos work? don't see how this could be beneficial to anyone since most of use are using copyrighted content.

**Comment by haizrul** [comment]
> Hello. i've done some tweak to bypass this limit. it can be fixed, we still have hope, you can use my free api by calling at this link:
> [http://gdriveplayer.us/embed2.php?link={enter](http://gdriveplayer.us/embed2.php?link=%7Benter) your limited google drive link here}
> 
> please send feedback if you find any error. thanks

Hi sir. Very good tool you have there. Thanks a lot for sharing. I'm using it now. 👍

**Comment by Parth-Gupta10** [comment]
> Hello. i've done some tweak to bypass this limit. it can be fixed, we still have hope, you can use my free api by calling at this link:
> [http://gdriveplayer.us/embed2.php?link={enter](http://gdriveplayer.us/embed2.php?link=%7Benter) your limited google drive link here}
> 
> please send feedback if you find any error. thanks

i get an error video
